### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by domoritz** [fisherman/fisherman#169]
After reading https://medium.com/@robbyrussell/d-oh-my-zsh-af99ca54212c I think two simple additions could increase engagement. One is that when you update fisherman or a plugin, a short description of the changes  (commit messages/ what files have changed) could be shown (#168). Second, fisherman could automatically update every other week to make sure that people stay up to date with the latest and greatest (this issue).

**Comment by bucaran** [comment]
@domoritz Rather than adding this functionality right into Fisherman, I'd rather create a plugin that only users willing to let Fisherman update itself can run. What do you think?

**Comment by domoritz** [comment]
I think a lot of people will not update then. I think it would help to have an auto updater that updates even very infrequently.

**Comment by bucaran** [comment]
What do @jethrokuan @orangecms @pickfire @herrbischoff @rolyreyes think?

I don't like the idea to update automatically, maybe just show a notification "there is an update available"?

What do other plugin/pkg managers do?

**Comment by domoritz** [comment]
> I don't like the idea to update automatically, maybe just show a notification "there is an update available"?

Definitely. Never update without the user's consent. I was thinking about "There is an update available. Do you want to install it? [Y/n]"

**Comment by orangecms** [comment]
Updating Fisherman should only happen on the user's demand, preferably through their system's package manager (apt, pkg, zypper, portage, pacman, you name it) as they are used to that.

**Comment by domoritz** [comment]
> Updating Fisherman should only happen on the user's demand, preferably through their system's package manager (apt, pkg, zypper, portage, pacman, you name it)

Then the preferred way should be to install fisherman through a package manager. Right now the recommended way to to run `curl -sL get.fisherman.sh | fish`. Also, how would that work on OSX and Windows?

**Comment by orangecms** [comment]
OSX has Homebrew, and on Windows I think there is cyg-apt or something like that.

**Comment by herrbischoff** [comment]
> I think a lot of people will not update then.

What's the issue with that? Just because you (or anyone) feels that everyone should use the latest version, does not automatically make it the right approach for everybody. Certainly this is no reason to annoy people into updating. Besides, we're talking about shell-savvy people here, not mainstream customers who are getting notified to update to the latest iOS — and even that is a one-time affair, despite the looming badge many still don't update right away, although eventually.

I agree that an official Homebrew package may be beneficial although that needs to be updated for every release and will do very little besides running the install script. Another point of irritation (for me at least) would be installing a framework via a package manager.

> Yes, the system's package manager should always be preferred. OSX has Homebrew, and for Windows there is apt-cyg. The only thing is that people need to write the packages.

Should this point to using the Homebrew infrastructure to install not only Fisherman but also its plugins, I'm strongly against it. This would be overkill, besides that fact that you would need to have a separate tap that in turn would be under the control of the Homebrew team. This effectively means giving away the plugin management and therefore all decisions about what gets included. Not to speak of the added burden of creating a Ruby-based formula to install a shell extension. I don't think this is reasonable.

**Comment by pickfire** [comment]
@bucaran, I don't support auto update. The update process is fast currently and can run in parallel. The user can just use a timer to set auto update.

**Comment by orangecms** [comment]
@herrbischoff If Homebrew is that weird and complicated, that's a fair point. I thought it was more evolved. The benefit would be a clean home dir and install/uninstall procedure without (what package managers have been invented for anyway), which is why I created the AUR package, done easily. I also write packages for portage (Gentoo's port/package manager), which is also straightforward. Is it really that hard with Homebrew?

**Comment by jethrokuan** [comment]
I think auto updating can come as a plug in,  so it's something users can
opt in to have. It's not something I'd use personally either.

**Comment by herrbischoff** [comment]
@orangecms: [Here's](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fish.rb) the installation formula for fish for comparison. It's not exactly hard since you run `brew create <URL>` and get a template. It's just that updating this every time you make a small edit and would need to release a new minor version adds significant overhead. Plus, the pull request has to be made to the Homebrew repository for each change. While it is possible to have HEAD-only formula, those are not updated automatically when running `brew update --all` and need to be updated manually through `brew reinstall --HEAD <formula>`.

I support auto updating as a plugin, should anyone feel the need to actually create it. I wouldn't use it though.

**Comment by bucaran** [comment]
I agree with @herrbischoff on this one, as a plugin, that is, an official plugin that would be accepted into the index, it would not bother me at all, so if anyone wants to take a shot at it, ping me directly on the Slack channel and I'll gladly help out the best I can.

Now, as a core feature, I vote :-1:

**Comment by orangecms** [comment]
@herrbischoff That looks just as easy as I expected, so with the proper Makefile that would be possible with fisherman as well. It's by design that software hits repos after the package maintainers' review, so if users really want to update from HEAD (where a package maintainer cannot be blamed) it becomes the user's own responsibility when something breaks, which is exactly the same as when they use the shell script. So if we just provide a proper Makefile, the Homebrew formula wouldn't need any maintenance at all (that'd be the same for any package manager actually). Users always benefit from a clean installation state.
So writing an updater would just mean extra work (though basically git fetch/merge etc., which again might fail if users do stuff with the cloned repo, move it, or whatever). As a plus, dependencies can be dealt with properly, like git currently (where the user would in case of an outdated version just see a hint and maybe be pissed), or fish later when the conf.d feature hits the next release and we want to support it. They'd want/need an older/fixed version of Fisherman then in case the don't want to/cannot upgrade fish for whatever reason (it might cause them other stuff to break, or depend on the sysadmin's/organization's policies etc.).

**Comment by kelvincobanaj** [comment]
I think that just showing a notification would be the best approach, since it doesn't disturb user and they can update when ever they feel like.

**Comment by herrbischoff** [comment]
Even then, I feel the notification should not be run automatically. To make that configurable and stay within the fish philosophy, it should be an optional plugin, as we already seem to have agreed on.

**Comment by bucaran** [comment]
Alright, thanks @domoritz for bringing this up and thanks everyone for their comments.
