### ISSUE TITLE
fin + fisherman?

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#204]
@fisherman/all 

Recently, I released [fin](https://github.com/fisherman/fin) as an experiment, something along the lines of fisherman 2.0 and I am confident it's a step forward from what started a few months ago with fisherman.

It would be fantastic if we could merge these two projects together. They are quite different internally, so keeping them both as separate would not hurt either and I just created this issue to get some feedback.

What are your thoughts on this?

**Comment by andrewrynhard** [comment]
What do you consider to be the strengths of each? Does either lack where the other is better? I do think merging them is a good idea. It was quite confusing as a user to figure out which will work better for me. I would imagine this could be a deterrent for some that could drive them away.

**Comment by dalln1** [comment]
I personally use fin and it does what it should do. No visible benefit of fisherman over fin for me.

**Comment by bucaran** [comment]
>  It was quite confusing as a user to figure out which will work better for me.

I screwed up. I should have just released fin as a new version of fisherman. It's a massive change, so I took the easy way out I am created a new project. But I am going to fix that now.

I am going to merge fin **into** fisherman.

**Comment by andrewrynhard** [comment]
I like the name `fin`. Clean and simple, just like its implementation. To bad it has to go!

**Comment by bucaran** [comment]
The plan is to release fisherman 2.0 over the next hour. This is such a drastic change that we will jump from 1.5 to 2.0 in one go. Internally, it will exactly the same as fin, but with a different name and an even simpler CLI with fewer colors and flashy things.

WRT to the name, I'd like to go from `fisher -> fin -> f`.

**Comment by detailyang** [comment]
+1 
agree with @bucaran  merge these two projects together !!!! :grin:

**Comment by sotayamashita** [comment]
@bucaran Is there any exactly definition of both ? I also use fish and fisherman but I am not sure. If they can be merge is the best but if we can not, I would like to define.

**Comment by andrewrynhard** [comment]
I think you have something good going on with the theme of `fisherman`. The log outputs (`argh`), the package names (`sharl`, `fishtape`). The whole vibe attracted me. IMHO `f` takes away from that. Ultimately it is just a name, but that is my two cents. I think a merge is a great idea.

**Comment by bucaran** [comment]
@sotayamashita Well, fin was an experiment and the results show it's more robust than fisherman, so we will just upgrade fisherman source code to use fin's source code, and bye bye to fin. It's hard to define both, but in terms of features they are almost the same. 

The only thing that will be missing is the search command.

**Comment by bucaran** [comment]
> I think you have something good going on with the theme of fisherman

Thanks. That's why we are keeping this repo. Also, the "fisherman ecosystem" is a theme that I want to keep as well.

**Comment by dalln1** [comment]
I already use `f` as an alias for `fin`. So I can remove the AUR package for fin? (I wrote you @bucaran  an email about that, but as I see, not the best idea :smile: ).

**Comment by bucaran** [comment]
It's easier to create an alias for fin/fisherman to `f`, than the other way around though.

We could ship 2.0 with `fisher` as the CLI command and if the user wants to, they can create an alias for it.

What do you think?

**Comment by orangecms** [comment]
Exactly!

**Comment by sijad** [comment]
why search command will be missed?

**Comment by bucaran** [comment]
Because it will not be present in 2.0.

I will not actually "miss" it however :)

**Comment by sijad** [comment]
Upgrading to 2.0 will be smooth?

**Comment by bucaran** [comment]
Good question. I don't think it will as smooth as previous upgrades. In fact, it may be impossible by the fact that 2.0 is entirely different and sits in a different directory too.

On the other hand, installing it will be very simple, so I am not worried about that.

**Comment by bucaran** [comment]
https://github.com/fisherman/fisherman/tree/2.0.0

**Comment by dalln1** [comment]
> https://github.com/fisherman/fisherman/tree/2.0.0
Will the installation be like stated here?

**Comment by bucaran** [comment]
Yes. Exactly like this:

```
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman
```

**Comment by orangecms** [comment]
On ArchLinux it will be smooth. I will provide a non-git version when we have the Makefile merged. Then you can just use your favourite AUR helper to upgrade smoothly. However, since the API changes, scripts building on top of them (like the search function) will not work anymore or work differently. ;)

**Comment by alphapapa** [comment]
Just a couple of cents here:

1.  I noticed that the fin repo is gone, gone, gone--well, all of the commits are.  I understand you wanted to fold it into fisherman instead, but man, if I had started to use fin since you told me about it, and I had spent any time setting it up, I'd be rather annoyed that the repo was wiped out, leaving me hanging.  This kind of thing is why I always feel like, if I don't fork a project as soon as I find it, the author might yank it out from under me.  Instead of wiping out all of the commits, you could have just made a new commit that boldly proclaimed that it is deprecated and now part of Fisherman 2.0.

Knowing that you've done this in the past makes me leery of using your other projects in the future.  Yes, I know fin was your experiment, but it was also released in a polished-looking repo, which communicates "you should use this!" to people.  And anyone who did will now be sinking into the ocean to rest with the fishies.  D:  So, you might want to consider this in the future.

2.  I also recommend against naming the project or the executable `f`.  Generally such short names should be left for user abbreviations.  For you, the project author, you're not going to forget what it's called, and you don't need to google for it.  But for a user, especially one who installs some stuff and then doesn't touch it for months, `f` is not very memorable nor googlable.  Besides, let Fish's tab autocompletion have a chance.  ;)

3.  Please consider signing your tags.  It's very easy and gives some simple protection against MITM and other attacks.  GitHub even makes it look nice, e.g: https://github.com/alphapapa/helm-org-rifle/tags

**Comment by bucaran** [comment]
@alphapapa Hey

1. Yup, that was frankly reckless from my part. What will happen is fin will just be renamed `fisherman`, merged into this repo and released as fisherman 2.0.

2. Yeah, we discussed this at length on the slack channel. It will go on as `fisher` like you say.

3. I added my gpg key to github, is there anything else I need to add so my commits are signed?

**Comment by alphapapa** [comment]
> I added my gpg key to github, is there anything else I need to add so my commits are signed?

You need to tag your releases (which I think you're already doing), and then sign and push the tags.  In Magit it's as simple as `t -s t`, then push, for a new tag.  If you're signing a tag that you've already pushed to GitHub, you'll have to force the tag creation (`t -s -f t` in Magit), and then force-push the tags like `git push origin --tags --force` (Magit doesn't seem to like force pushing tags for some reason).

**Comment by pickfire** [comment]
@bucaran, I like the merge but I like the name `fin` more than `fisherman` or `fisher`. So sad to see `fin` went out just like that. :sob:

**Comment by alphapapa** [comment]
I guess this is the end of `fin`.

...

:D  

...

I mean, D:

**Comment by bucaran** [comment]
The only thing that is going to change is the name, and while I like `fin` more too, the brand fisherman is more attractive, so it's just a little compromise.

The good news is that now everyone can benefit from fin, because fisherman will evolve into fin.


@pickfire 

Don't worry, he lives in you...


![screen-shot-2015-07-27-at-11-47-20-pm](https://cloud.githubusercontent.com/assets/8317250/14710783/c12c7ec4-0811-11e6-91ab-707ecce102a6.png)

**Comment by bucaran** [comment]
> @alphapapa I guess this is the end of fin.

I don't know, we still have the repo, and the logo. We can make something useful with that name. Just, not a plugin manager :)

**Comment by alphapapa** [comment]
I was just making a pun on fin/end, but yeah, that sounds like a good idea.  :)

**Comment by bucaran** [comment]
> I was just making a pun on fin/end, but yeah, that sounds like a good idea. :)

Ahhhh, right, good one

**Comment by daenney** [comment]
Just create an alias or abbrev or function that returns fin to you 😄

**Comment by pickfire** [comment]
@bucaran, thanks a lot for that. :smile:

**Comment by bucaran** [comment]
@alphapapa It took me a while to get through gpg, but I am happy. You'll never guess my passphrase.

<img width="1087" alt="screen shot 2016-04-22 at 12 58 45 am" src="https://cloud.githubusercontent.com/assets/8317250/14715772/1e67c392-0825-11e6-9fad-dc4109b71680.png">

**Comment by bucaran** [comment]
c390b0b

**Comment by alphapapa** [comment]
@bucaran Hmm, sounds fishy to me.
