### ISSUE TITLE
[Idea] fisher info

### ISSUE THREAD

**Issue by Nolski** [fisherman/fisherman#236]
There was some discussion in the slack about adding a command that works something like `brew info`. The user story goes along the lines of the user listing through many different plugins and themes available in the fisher index and they want to find relevant information on the listed plugin. The output of `fisher info <plugin_name>` should look something along the lines of 

```
<plugin_name> [plugin | theme | etc]
Here is a description of the plugin which is provided by the package owner. 
Perhaps they could also place the output of the help information. 
Or perhaps if it's a theme it could just print out an example terminal output of the 
theme.
```

**Comment by bucaran** [comment]
Currently

```
bucaran@mbp ~/c/fisherman> fisher ls fin
/Users/bucaran/.config/fisherman/fin
    .gitignore
    .travis.yml
    completions/
        fin.fish
    conf.d/
        fin.fish
    fishfile
    functions/
        __fin_index_update.fish
        __fin_list.fish
        __fin_rm.fish
        __fin_run_bin_as.fish
        __fin_usage.fish
        __fin_use.fish
        __fin_version_download.fish
        __fin_version_local.fish
        __fin_version_query.fish
        __fin_version_validate.fish
        __fin_version_which.fish
        fin.fish
        node.fish
        npm.fish
    README.md
    test/
        fin.fish
```

lists the directory contents as you can see.

Instead of introducing a new command, I propose to keep the same semantics, and use `ls-remote` instead.

```
fisher ls-remote fin
fin
node.js version manager in fish-shell
81
github.com/fisherman/fin
```

@Nolski What do you think?

**Comment by laughedelic** [comment]
I think that `ls-remote` command for information is rather confusing. The name is not intuitive and then it's kind of against the "discoverability" principle, isn't it?

**Comment by Nolski** [comment]
I'd agree with @laughedelic (although to be honest, I'm not super picky about it) It might be cool to print the actual prompt if it's a theme (do we use that term now?). I'm not sure how simple that would be though.

**Comment by bucaran** [comment]
@laughedelic Yeah, but adding a new command for something arguably secondary, like getting the plugin's description would set a precedent. Like, if we have `fisher info`, why not `fisher init` or `fisher new` or `fisher submit`.

Some people love to over complicate things and I'd like fisherman to always remain simple and uncomplicated.

**Comment by bucaran** [comment]
@laughedelic The correct term is "prompt". I didn't make it up, it's what fish-shell calls it e.g., fish_prompt, fish_right_prompt. A theme would be a combintation of the prompt + `fish_color_*` uvar colors + terminal color palette. 

As as matter of fact, fisherman does have full themes that have all of the above, for example, [joker](https://github.com/fishery/joker), terran, stark, superman, etc.

**Comment by detailyang** [comment]
like more `fisher ls fin` to show plugin directory  and `fisher info fin` show description

**Comment by bucaran** [comment]
@detailyang What about adding a man page to your plugins?

Currently fisherman allows you to do this

```
fisher help my_plugin
```

and that will show you not just info, but all the info the author has for you.

**Comment by bucaran** [comment]
Ping @chuenlungwang :)

**Comment by bucaran** [comment]
https://github.com/fisherman/fisherman/commit/74b579e8d3a08810ae62a55943e5a5ee2a6c49b6

@Nolski This is what I came up with.

```
bucaran@mbp ~/c/fisherman> fisher ls-remote z
Pure-fish z directory jumping.
github.com/fisherman/z
```

**Comment by Nolski** [comment]
I like it! Thanks! 😄

**Comment by bucaran** [comment]
@Nolski You can customize how the list output too:

```
fisher ls-remote --format="%name ★ %stars\n| %info\n| https://%url\n" z
z ★ 15
| Pure-fish z directory jumping
| https://github.com/fisherman/z
```

**Comment by laughedelic** [comment]
> adding a new sub command for something arguably secondary, like getting the plugin's description would set a precedent for adding even more sub commands

I understand that you want to keep things simple and minimize the number of different subcommands. But then why having a separate `ls-remote` command? 

Here's what I suggest: `ls-remote` should be smth like `fisher ls --remote` (or `-r` for short or whatever). Then `ls` has clear semantics: showing information about fisherman plugins in general. Now _which_ information and _how_ should be controlled by its options. For example:

- `fisher ls` shows installed plugins (as now)
- `fisher ls --remote` shows (in the same format) all plugins in the index that are _not installed_ (otherwise why `remote` and not `all`?)
- `fisher ls fin` shows fin's content (as now) (I personally, don't understand why this is useful, but whatevs)
- `fisher ls --info [--remote/--all]` shows a verbose list of plugins with their information (local or remote/all with corresponding options). `--info` could be just an alias for some `--format="..."`
- `fisher ls --info fin z simple` same, but shows info only for these plugins

If somebody wants this shorter, they can always make an alias or something (choosing preferable format as well).

P.S. btw, at the moment, if I type `fisher ls z simple` it only shows content of `z` and ignores `simple`.

**Comment by bucaran** [comment]
Yes, `fisher ls z simple` will only list the first argument. I think I could work on adding support for multiple arguments without much trouble. 👍 

The reason for `ls-remote` instead of `ls --remote` is because it's easier to type (thanks to completions) and because it's easier to parse since we have decided to avoid using a CLI parser in the fisherman implementation for performance.

Using --long flags also means more complex completions as well as more stuff the user needs to remember. ls-remote will show up when you hit `fisher <tab>` and while it ***is*** a new command, it's keeping the same semantics with `ls` so depending on someone else's point of view, you may see it as an extension of `ls` as well.

> I personally, don't understand why this is useful, but whatevs

I don't find it extremely useful either, but I do use it sometimes when debugging or wishing to see what files are in the plugins master directory.

**Comment by laughedelic** [comment]
> it's easier to parse / implement now that we are not using a CLI parser, mostly for performance reasons. The main fisher function is already pretty heavy.

This is all implementation details that, I believe, shouldn't influence usability.

I generally disagree about "easier to type" (especially taking into account that options can be also autocompleted). When I type `fisher ls-remote`, I need to type `fisher ls` anyway, so what's the difference? one space to type `fisher ls -<tab>`? Why not to make it a separate command then?

> it is certainly a "new" command, it's also keeping the same semantics with ls

I think these two things shouldn't be mixed: either it's a new command with another name (which then is easy to type and complete), or it's a variation of ls which should be an option then.

> I don't find it extremely useful either, but I do use it sometimes when debugging

Then why is it the shortest command (in this context)? I think `fisher ls fin` should show information, instead of `fisher ls-remote fin`, while some functionality for debugging should be hidden under some flag not to confuse user.

Anyway, it's all just my opinions.

**Comment by laughedelic** [comment]
P.S. I wanted to ask from the beginning, why have you decided to include this as a core functions and not make a "search"-plugin as you were suggesting before?

**Comment by bucaran** [comment]
> P.S. I wanted to ask from the beginning, why have you decided to include this as a core feature and not make a "search"-plugin as you were suggesting before?

To make fisherman more useful out of the box, but keeping the same semantics used already.

>  I think fisher ls fin should show information

Ls *lists* what you have installed (local information). The most common use for ls is to show what plugins are currently enabled. Also, if you use `ls a b c`, it behaves like the `ls` UNIX command. I don't find this behavior unintuitive, maybe a bit odd yes, but it should not come as a surprise to anyone.

Ls-remote *lists* what you could install (that is also currently **not** installed), so it's clearly about remote information. The most common use should be, just like ls, to show what plugins the user could install / download.

I needed this feature to be a separate command, but not something like "info". If you type `fisher ls<tab>` you will get two alternatives. When the user sees `ls and ls-remote`, they should expect these two commands to behave similarly, whereas with `fisher info` I would need to run it first in oder to see exactly  how it behaves.

Ls-remote also takes a flag, *--format=string*. If it was fisher ls --remote, then I am not sure what would be the best way to specify the format string.

Finally, ls-remote a b c, just like its ls counterpart, also have a meaning, to list remote information.

FWIW, this is undocumented, but "fisher info" is also an alias to ls-remote (internally).
