### ISSUE TITLE
`fisher ls-remote` hides installed packages

### ISSUE THREAD

**Issue by colstrom** [fisherman/fisherman#250]
Actual:
```
$ fisher ls-remote
foo bar baz

$ fisher install foo

$ fisher ls-remote
bar baz
```

Expected:
```
$ fisher ls-remote
foo bar baz

$ fisher install foo

$ fisher ls-remote
foo bar baz
```

There's currently no way to show all available packages, including those already installed. It may be reasonable to hide this information from the user, but seems less reasonable to be completely inaccessible. Perhaps different behaviour when STDOUT is a TTY, and when it is not?

There's reasonable cases to show or hide this, so it might make sense to have a pair of flags to control this behaviour?

`fisher ls-remote --show-installed` would force installed packaged to be displayed.
`fisher ls-remote --hide-installed` would force them to be hidden.

**Comment by bucaran** [comment]
> There's currently no way to show all available packages, including those already installed.

After #249 lands,

```fish
begin
fisher ls
fisher ls-remote
end | cat
```

will do it.

**Comment by bucaran** [comment]
@fisherman/all Thoughts?

Ping @jethrokuan @herrbischoff @orangecms @lordlycastle @Markcial @MadcapJake

**Comment by Markcial** [comment]
Personally i would like to use the full color support to display what's going on on certain packages. So the installed packages would have orange color, the packages not yet installed would be green, the installed ones, blue. If the color support is not enabled then symbols would be appended/prepended to the packages.

Anyways it is true that ls-remote should not hide already installed packages if they are remotely available, let's take as example another package managers as yum, apt o pacman, they list available packages even the installed ones, but mark them with a letter or symbol so user notices that that packages are already installed.

**Comment by bucaran** [comment]
My logic is clearly expressed in the README.

See what's installed.
```
fisher ls
```

See what you can install.
```
fisher ls-remote
```

**Comment by Markcial** [comment]
following that kind of logic we might end up with a new action for listing the packages that can be updated.

I guess that listing packages that are available remotely includes the ones already installed, but maybe not as the ones that are not installed.

**Comment by bucaran** [comment]
That is the logic as it is written and described in the README since the feature was implemented and I don't see what's wrong with it.

And no, there will be no more new actions, there could be an internal `__fisher_*` like function, but I'd rather land #249 and then open the door to https://github.com/fisherman/fisherman/issues/250#issuecomment-216631163.

I am not very fond of `--show-installed` or `--hide-installed` either.

**Comment by MadcapJake** [comment]
@Markcial, @colstrom: what use do you two see in showing all packages (included installed)? "Other package managers do it" doesn't really explain what it's useful for.

**Comment by bucaran** [comment]
> @Markcial: Personally i would like to use the full color support to display

* fisher ls-remote --format=*string*

You can embed colors in that string and get the output exactly the way you want it, that's why the format string exists. See: https://github.com/fisherman/fisherman/releases/tag/2.2.0

**Comment by orangecms** [comment]
I'd also expect `ls-remote` to show everything and not just what's not installed. Otherwise it is misleading and I will not see if e.g. a package is removed. That is what I would understand now from the result. If I have something installed and `ls-remote` doesn't show it, it means that it cannot be installed, so it doesn't exist anymore. And yes, other package/pkugin managers wouldn't do this. They would rather show more verbose information and tell me in the list if a package is already installed, can be updated, etc.. Debian's `dpkg -l` for example even tells me if a package has once been installed, if it is installed now, and if I can just install it.

**Comment by bucaran** [comment]
I will implement #249 which is somewhat related to this ASAP. But since I don't have a solid use case for #250, this is unlikely to be implemented any time soon. I have added the `PR WELCOME`, so if someone wants to take a stab at it, they are more than welcome to do so. Also make sure to update the documentation and propose the CLI changes in advance.

**Comment by colstrom** [comment]
@MadcapJake "Other package managers do it" isn't a reason in itself, but it is a strong indicator of what a user is likely to expect. I found this behaviour to be very surprising, but I'm hardly a representative sample. ;p

- I can filter data I don't want.
- I cannot conjure data isn't there.
- This omission is deliberate, and silent.
- There is no mechanism to override this.

@bucaran I understand that the README says it works a certain way, though that feels a bit like circular reasoning: It's documented because that's what it does. It does that because that's what the docs say.

The way this is current implemented appears to have more limitations than benefits.

- It would be nice to be able to format remote packages based on their installed status.
- It would be nice to query ls-remote to see if a package name is currently in use.
- With a full list of packages, I could conveniently bulk-clone or update all the current packages, for offline use (I commute via train, and cell service along the route is spotty at best).
- The list could be used to present the packages in different ways (sorted by GitHub stars, for instance).

The point is that we can do all sorts of things with information we have, but miss out on that when the data is deliberately discarded. In my view, this is a case where fisherman assumes too much about how it will be used, resulting in default behaviour that is both counterintuitive, and counterproductive.

**Comment by bucaran** [comment]
So, what is your use case again?

**Comment by bucaran** [comment]
#257

**Comment by laughedelic** [comment]
From #257:

> - [x] Do not hide installed plugins in fisher ls-remote

I read some part of your long discussion on slack, but I missed the moment when @colstrom convinced @bucaran to make this decision. What's the reason? (I'm just curious)

**Comment by bucaran** [comment]
Well, in a way, you convinced me with https://github.com/fisherman/fisherman/issues/256

If we are going to use the index as the source of completions, there is no longer a need to hide installed plugins in ls-remote, since that will be the default behavior when auto completing the pager.
