### ISSUE TITLE
fisherman crowds functions directory

### ISSUE THREAD

**Issue by andrew-kennedy** [fisherman/fisherman#254]
By default, `funcsave` puts user functions in `~/.config/fish/functions`, just as fisherman does. The problem is, whenever I look inside this directory, I can't tell at a glance which files I created and which ones came from fisher plugins. Is it possible for fisherman to place it's functions in a subdirectory, or otherwise to override the behavior of `funcsave`?

This also makes backups more difficult.

**Comment by bucaran** [comment]
The only way to know whether it's a function you created or it's a function from a plugin installed with fisherman is that the latter is a symlink, whereas the first one is probably a regular file.

When you install a plugin from a directory, and run fisher ls, you know it's a directory/symlink because it is displayed as `@ plugin_name`.

>  Is it possible for fisherman to place it's functions in a subdirectory, or otherwise to override the behavior of funcsave?

That would require you to modify your configuration, and zero configuration is one of fisherman goals. 

So, for better or for worse, fisherman is opinionated about this. The rationale is that you are arguably better off using fisherman to create plugins, from urls, gists, local directories, etc., instead of using funcsave.

Mind you, you can still use funcsave just fine, since that saves the function as a regular file, but then you are responsible for managing that function yourself.

**Comment by laughedelic** [comment]
@andrew-kennedy I solved it by putting all my functions (configuration and aliases) in a [separate place](https://github.com/laughedelic/.fish) and installing them as a plugin. This is quite convenient, because I don't touch `~/.config/fish/` anymore. All my configs any functions are just another plugin.

I don't use `funcsave`, just create files with functions and edit them, but I think it's easy to make a function for saving your function definitions in a certain place. Something like this:

```fish
function myfuncsave -a name -d "Saves function 'name' in my favorite place"
  functions $name > ~/my/functions/$name.fish
end
```

(just as an example, if you want to add some error handling, see `functions funcsave`)

**Comment by bucaran** [comment]
@andrew-kennedy I think @laughedelic's approach is the best in this case.

The reason fisherman works great out of the box is because we are opinionated about some things, but if this behavior is not desirable we could introduce a new `fisher_prefix` variable to let users customize the location where functions, completions and scripts are saved to. 

Obviously, users would also be responsible for adding that prefix to the fish_function_path.

What do you think?

**Comment by laughedelic** [comment]
> I think @laughedelic's approach is the best in this case

I'm going to write a readme in my repo explaining my setting. Could be probably useful for #259.

**Comment by andrew-kennedy** [comment]
@bucaran I honestly didn't think about turning my functions into a fisher plugin because I'm so used to doing things the old fish shell way. I like that idea and will probably do that. That will make it easy to just include it in my fishfile and makes dotfile backups even easier. 

The `fisher_prefix` variable is probably a good idea as well though.

**Comment by bucaran** [comment]
@andrew-kennedy Thanks. So, let's do this. Try the fisherman approach and see how it goes. Adding a variable now, would not mean a lot much and we can always add such config option in the future if enough people want the feature.

**Comment by bucaran** [comment]
Closing as resolved, but open to the possibility of adding this variable in the future as we get more feedback.

**Comment by brj** [comment]
@andrew-kennedy This may be of your interest :)
https://github.com/fisherman/fisherman/issues/301

**Comment by powelleric** [comment]
I'm not quite sure where this issue left off but I would definitely be interested in a 'fish_prefix' type variable that would allow functions to be linked into a directory of the user's choosing (and then the user would add that dir to their $fish_function_path).

Personally, this would allow me to keep my .config directory under git control and not have to worry about adding all of the linked functions to my gitignore file.

As a side note, this might actually be the more fish-y way of handling things.  The documentation specifies different directories for the functions of end-users and the functions of third-party vendors.  I would have expected fisherman to make it's links in the vendor directory.

> A directory for end-users to keep their own functions, usually ~/.config/fish/functions (controlled by the XDG_CONFIG_HOME environment variable).
> A directory for third-party software vendors to ship their own functions for their software, usually /usr/share/fish/vendor_functions.d.

P.S.  Thanks a bunch for all your hard work.  I really, really appreciate it!

**Comment by jbucaran** [comment]
@powelleric And [`fish_path`](https://github.com/fisherman/fisherman#where-does-fisherman-put-stuff) is not enough for what you are trying to do? 🤔

**Comment by powelleric** [comment]
@jbucaran  Maybe I am doing something wrong.  `fish_path` is only changing where fisher downloads the package but then it still symlinks to ~/.config/fish/functions.  

I'd actually be happy to disable the linking altogether and just add the fisherman path to my `fish_function_path` but being able to control the directory for linking would be good, too.

Thanks a bunch for your reply!
