### ISSUE TITLE
Auto suggestion and Error Management

### ISSUE THREAD

**Issue by namandistro** [fisherman/fisherman#27]
I don't know about others but i am feeling lag its not that smooth sometime and their should be something for error management

**Comment by bucaran** [comment]
Could it be that you are experiencing the initial, first time only lag when auto complete/suggestion is updating?

Other than that Fisherman should always outperform other systems, is just as fast as having nothing at all, but the first time you try to auto complete, there will be a small lag as fish updates the auto complete so that you can do things like:

```
fisher install <tab> [ packages you can install show up here ]
fisher update <tab> [ packages you can update show up here ]
fisher uninstall <tab> [ packages you can uninstall show up here ]
```

Notice that is not as trivial as Wahoo or Oh My Fish! because Fisherman generates completions for all plugins, those in the [Index](https://github.com/fisherman/fisher-index) as well as those you install via a custom URL.

**Comment by bucaran** [comment]
Major speed improvement to land in 0.3.0. Thanks for suggesting this @namandistro.
