### ISSUE TITLE
How to install OMF theme with the fisherman?

### ISSUE THREAD

**Issue by cyrillk** [fisherman/fisherman#278]
```
❯ fisher omf/clearance                                                                                                                                   INFO Installing 1 plugin/s
ARGH Fetch clearance github.com/oh-my-fish/plugin-clearance
ARGH There was an error installing clearance or more plugin/s.
INFO Try using a namespace before the plugin name: xxx/clearance
```

**Comment by bucaran** [comment]
@cyrillk 

You need to use the same prefix omf uses `theme-`.

```
fisher omf/theme-clearance
```

That should do it.

**Comment by cyrillk** [comment]
Thanks! Yes, it works. Though it's not obvious unfortunately. Documentation suggests to install plugins as `fisher omf/tab` but not `fisher omf/plugin-tab`.

**Comment by bucaran** [comment]
Yep, you are right. It's not obvious at all. 

When I wrote this bit, I thought: "what are users most likely to install from omf; plugins or themes?" So, fisherman favors plugins over themes, but there is no good reason for that really.

To be honest, this has been bugging me for a while. Since there is no way to guess whether an omf plugin is a theme or not, perhaps we can use brute force and try with `theme-` if the previous request fails when the url is oh-my-fish.

What do you think?

**Comment by cyrillk** [comment]
Ok, I see. 

I can update the code and send a pull request on it. If it is ok for you.

**Comment by bucaran** [comment]
It's perfectly okay with me. If you figure out how to do this, I'd love to merge this feature.

**Comment by cyrillk** [comment]
Cool. I'll give it a try )
