### ISSUE TITLE
Plugins not working

### ISSUE THREAD

**Issue by rif** [fisherman/fisherman#29]
For the moment fisherman is not executing my plugins.

I reinstalled it but the problem still persist. 
Another thing is that I tried to uninstall some of the plugins to check if there is a particular one that is generating an error and brakes the initialization chain but it does not seem to be uninstalled:

❯ fisher --cache
/home/rif/.config/fisherman/cache/fasd
/home/rif/.config/fisherman/cache/fzf
/home/rif/.config/fisherman/cache/pure
/home/rif/.config/fisherman/cache/tmux
                                                                                
~ 
❯ fisher uninstall tmux
Uninstalling >> tmux
1 plugin/s uninstalled (0s)
                                                                                
~ 
❯ fisher --cache
/home/rif/.config/fisherman/cache/fasd
/home/rif/.config/fisherman/cache/fzf
/home/rif/.config/fisherman/cache/pure
/home/rif/.config/fisherman/cache/tmux

Can you suggest some troubleshooting steps?

Thanks a lot,
-rif

**Comment by rif** [comment]
Something I tried just now:

1. moved ~/.config/fish and ~/.config/fisherman in a backup folder
2. started a new fish shell
3. executed make in fisherman repo
4. fisher install omf/plugin-fasd
5. z alias is not active after reset or terminal restart
6. fasd is not uninstalled after fisher uninstall fasd

I am using arch linux amd64 with fish 2.2.0

**Comment by bucaran** [comment]
Aye! Alright, let's go one by one. Can you confirm you used the correct URLs?

Pure actually works for me:

```
fisher install rafaelrinaldi/pure
```

**Comment by rif** [comment]
pure is the only one that is working for me too

**Comment by bucaran** [comment]
Thanks! I need to investigage further. The architecture to support OMF is there, but there may be bugs of course.

This the source code of [fzf](https://github.com/gretel/pkg-fzf). I need to see what's happening there too.

**Comment by rif** [comment]
Thank you a lot, If you need me to do any tests just let me know.

**Comment by bucaran** [comment]
Yes. Things will start to take good shape as soon as I release 0.3.0 my captain!

**Comment by bucaran** [comment]
Wow, I just found this.

https://github.com/fisherman/fisherman/blob/master/functions/fisher_uninstall.fish#L80

I have no idea how that slipped in there :sweat_smile: 

That is effectively removingt the files from the cache every time you uninstall something.

**Comment by bucaran** [comment]
I also found out that the changes introduced in 0.2.0 were causing the code that determines whether the item gets appended to the fishfile or not, to fail. Basically, since 0.2.0, you can search not only indexed plugins, but also stuff locally installed.

For example, even though @rif pure theme is not in the [INDEX](https://github.com/fisherman/fisher-index) (and whether it should or not is an entirely different subject), here is what happens if I type:

```
❯ fisher search --name=pure
pure
https://github.com/rafaelrinaldi/pure
rafaelrinaldi/pure
orphan
dev+github@edouard-lopez.com

~/src/fish-get master*
❯

```

**Comment by bucaran** [comment]
@rif Can you upgrade and try again? Let's see if this is fixed or what else needs to be done.

**Comment by rif** [comment]
I can confirm that pure and fasd are working properly but gretel/fzf is still not working.

**Comment by bucaran** [comment]
Good news! 

fzf will be supported as soon as I can release the omf compatibility plugin. Below is the rationale.

This plugin uses an `init` event. I am actually the party responsible for introducing events into OMF, as I did originally in Wahoo. [See here](https://github.com/bucaran/wahoo/blob/master/init.fish#L44). 

This was probably a poor decision :sweat_smile:. 

Events are inherently slower than a simple  `source file` and it just not [possible](https://github.com/fish-shell/fish-shell/issues/2665) to parse the output produced inside an event handler.

Fisherman modifies `init.fish` files into `*.config.fish` files (`ls $fisher_config/conf.d`) and loads then during startup, but emitting events would will not be supported by default due to performance implications. Using the omf plugin should among a few other things, emit these events, making fzf work just fine.

**Comment by rif** [comment]
I understand that it hurts to drop speed and I think if this omf compatibility plugin will be optional for those that want specific plugins can be a good trade-off.

Meanwhile I am torn between using fish with fisherman with fish or zsh with [zgen](https://github.com/tarjoilija/zgen). :sweat_smile:

**Comment by bucaran** [comment]
Why not both? I use `zsh` too (sort of). I have been trying out   https://github.com/b4b4r07/zplug a bit lately.

**Comment by fiatjaf** [comment]
I have just experienced similar problems with `fisher install oh-my-fish/fasd`. I'll wait for news in this issue.

**Comment by bucaran** [comment]
@fiatjaf I believe the correct url for that plugin is `plugin-fasd`.

You can simply type:

```
fisher install omf/plugin-fasd
```

Now, the plugin `fasd` uses OMF slow events, so you will need the `omf` compatibility plugin for this to work. The problem that plugin is not available yet. Unfortunately you will need to wait at least another day before I can release it with 0.5.0.

Hold on there :smile:

**Comment by fiatjaf** [comment]
`oh-my-fish/fasd` has installed it, I think. Or at least it showed a message saying it was installing. Anyway, I'm not sure, but thank you. I'll wait. I'm just starting to get used to these plugins and fancy stuff -- not sure yet if I should become dependent on this or if I should stay with my raw fish shell.

**Comment by bucaran** [comment]
We are always learning. When I started contributing to OMF my ideas about that a "shell plugin" should be were very different. I would like to convince you and others that (1) using plugins instead of monolithic dotfile solutions to share your functions, tools and configurations is the way to _shell_, but (2) I believe we are making a mistake by having a `fasd` plugin.

The [omf/plugin-fasd](https://github.com/oh-my-fish/plugin-fasd/blob/master/init.fish) does not make a lot of sense. **First**, it should not define any aliases, that's up to you to decide. **Second**, it should not use Fish events and make your slew unecessarily slow, and **third**, its name should ***not*** be `fasd`.

The omf/plugin-fasd is a particular's user opionated way to use `fasd`, which I probably won't use.

Which should be the best way is up to you to decide.

**Comment by fiatjaf** [comment]
Alright, thank you. It's probably better to decide after listening to some hard opinions instead of not knowing anything.

**Comment by bucaran** [comment]
Right, also fasd is written in bash, which I guess is why people are creating a plugin to wrap it and make it work on Fish.

Nothing wrong with that. I think fasd should be rewritten in AWK or Perl so that it was easier to port to other shells. It would be faster this way too.

**Comment by kiRach** [comment]
:+1: Can't wait! :)

**Comment by bucaran** [comment]
Hi @kiRach What OMF plugins are you using?

**Comment by kiRach** [comment]
Hi @bucaran, I was going to use z plugin (https://github.com/oh-my-fish/pkg-z) but it didn't work well. I found this thread and think that's because of omf events you've already talked about.

**Comment by bucaran** [comment]
Yes. That plugin uses events. I don't use `z` so you could really help me debug this as soon as I am ready to ship a fix for plugins that use events.

**Comment by kiRach** [comment]
@bucaran No problem, let me know when you will need my help.

**Comment by bucaran** [comment]
Awesome. I'll give you a ping sooner than later, perhaps later today. If you could sign up [here](https://fisherman-wharf.herokuapp.com) that would be even more helpful.

**Comment by bucaran** [comment]
@rif @fiatjaf @kiRach @simnalamburt We should have close to 100% compatibility with Oh My Fish! packages now using the [`legacy`](https://github.com/fishery/legacy) plugin.

![legacy](https://cloud.githubusercontent.com/assets/8317250/12872034/f5767c34-cdd8-11e5-991a-90aa77c51645.gif)


7efb46bc10713096a49cf99ee38ddafd6d85ccee

**Comment by rif** [comment]
fisher install gretel/pkg-fzf it's only working on the same session you installed it on. After you close fish and reopen it fh alias is gone.

**Comment by rif** [comment]
❯ fisher -l
*autoinit
*available
*fasd
*fzf
*git-branch-name
*git-status
*legacy
*pure

**Comment by bucaran** [comment]
@rif Thanks for trying again!

I had a look at @gretel's [plugin](https://github.com/gretel/pkg-fzf/blob/master/fzf.fish) and tested it locally.

The problem is the plugin's functions are all written in the same file which has the same name of the plugin. This is probably one edge case I didn't consider.

If you `type $fisher_config/functions/fzf.fish` you will notice that `autoinit` has correctly added:

```fish
if status --is-interactive
    emit init_fzf $fisher_config/functions
end
```

But only files that go into `$fisher_config/conf.d` are evaluated during shell start.

The solution is to evaluate the file everytime. Let me see if `autoinit` can help.

In the meantime, I would like to recommend @gretel to modify the plugin or perhaps @rif can write a new `fzf` using better practices.

**Comment by rif** [comment]
For me searching the history is quite important. Do you know any alternatives to fzf?

**Comment by bucaran** [comment]
@rif 

* Fastest way, more developer friction: Create a new, more sensible `fzf` plugin and forget about the other.
* Slowest, less developer friction: I see if there is a solution using `autoinit` that just patches everything.

Would you consider writing a new `fzf`? We could put it in the [Fishery](https://github.com/fishery).

If you don't have time, I can do this for you, but it will take a few days.

**Comment by rif** [comment]
Oh, sorry way to little time on my part to writing a fzf plugin. I'm also not expecting you to write it.
If it's just the case of a badly written plugin that happens to brake my workflow on fish than we can forget about it. I can live quite well with zsh.

**Comment by ffittschen** [comment]
@rif I'm using fish shell but I didn't need any plugin for `fzf`. `fzf` already comes with [fish keybindings](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish) 
Did you install `fzf` like described on the `fzf` github page and run the install script?
```bash
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
```

The install script will create symlinks and all necessary stuff (but be aware, it creates everything for `bash`, `zsh` and `fish`! So after running the install script I removed the unnessecary config files like `.zshrc`)

you could also try to manually create a symlink: `ln -s /usr/local/opt/fzf/shell/key-bindings.fish ~/.config/fish/functions/fzf_key_bindings.fish`
(Check the first path, this is where Homebrew installed it for me. It probably is different when you installed it manually)

**Comment by bucaran** [comment]
@rif 

Try this https://github.com/bucaran/pkg-fzf/tree/master

**Comment by bucaran** [comment]
@ffittschen Thanks! I think that's one perfectly valid alternative and thanks for pointing this out. While I want to move my functions and snippets into plugins for better organization and sharing, creating plugins for a tool like `fzf` always felt **wrong**.
