### ISSUE TITLE
Merge fisherman/index into local cli cache

### ISSUE THREAD

**Issue by wk** [fisherman/fisherman#308]
Currently, the fisherman/index repository is used exclusively for the web-based search on [fisherman.sh](http://fisherman.sh). 

It would be pretty cool if packages from the index are also discoverable and installable via CLI, since at the moment, an invocation of `fisherman install <package>` for a package that's present exclusively in the index, but is not a repository under the `oh-my-fish` or `fisherman` orgs on Github will fail.

**Comment by wk** [comment]
A few points on the rationale of allowing some plugins to remain outside the `fisherman` org can be found [here](https://github.com/wk/plugin-ssh-term-helper/issues/1#issuecomment-223802549).

**Comment by brj** [comment]
Before 2.0, repos were read from fisherman/index. With 2.0, we started using the GitHub API to query the org/s, since maintaining an index was a lot of work and I wanted to make fisherman more of a "decentralized" tool. 

The index still exists for historical reasons and because the website still uses it for search. TBH, I was hoping to make the website use the GitHub API at some point to query orgs just like the current CLI does.

I think it would be really nice if fisherman used _all_ the available sources to populate the index. I still don't like the idea of having to maintain a central index, but if that's what people want, sure.

**Comment by laughedelic** [comment]
> I wanted to make fisherman more of a "decentralized" tool

What do you mean here by "decentralized"? Collecting all plugins in the same org seems to be the opposite..

I think that it can be a feature of fishkit to simplify how new plugins are submitted to the index. And what do you mean exactly by maintaining the index?

**Comment by brj** [comment]
PR Welcome.

**Comment by laughedelic** [comment]
@brj if PR is actually welcome, could we leave this open?

**Comment by brj** [comment]
This is not a trivial modification. If anyone really wants to take a stab at this, I'd be probably okay with it, but I don't want to leave this open here forever either.
