### ISSUE TITLE
fisher doctor (like brew doctor)

### ISSUE THREAD

**Issue by bbqtd** [fisherman/fisherman#318]
It would be nice if fisherman will have `doctor` for regenerating soft links regarding installed plugins without fetching update

**Comment by brj** [comment]
@bbqtd How do these dead soft links get generated?

**Comment by bbqtd** [comment]
One of cases is user changed (and moved folder content) `$fisher_path` directly for any reason. I believe at this moment `update` doing part of this job but with fetching update. Of course `update` in any time is better, but it would be nice have just `doctor` without `update` if something going wrong.

**Comment by brj** [comment]
Thanks. Do you think this happens often enough to require the doctor command? What about an arbitrarily complex solution via a plugin?

@fisherman/all Thoughts?

**Comment by Markcial** [comment]
IMHO would be something like a package manager but for "recipes" or "vaccines".

This means that if you have a missing conf.d loader script for example, doctor looks for the "missing_include_fix_vaccine" adds it and fixes the missing snippet with some sort of conditions the solutions can be done with snippets or includes.

Simply an idea, thoughts

**Comment by brj** [comment]
We should identify diseases first. How many do we know so far?

**Comment by Markcial** [comment]
I have found very few if not none. But this is because when I am done with getting my setup done I stop fiddling around. So my insight might be very biased because i tend to fix by myself issues I face around.

Anyways I posted the comment because one thing I love from fisherman is it's lightweight nature. This is why even do not having a lot of trouble with it, the doctor idea sounds nice for not so hardcore shell users. But again, the idea would be cool if we can't have granularity and all the "fixes" are not in the doctor plugin or inside the fisherman package manager itself.

My two cents.

**Comment by brj** [comment]
I proposed adding the project scaffolder functionality to core [some time](https://github.com/fisherman/fisherman/issues/245) ago. The conclusion was to add this functionality via a plugin, which is what we did with [fishkit](https://github.com/fisherman/fishkit).
