### ISSUE TITLE
Configure the directory of fisherman

### ISSUE THREAD

**Issue by chamini2** [fisherman/fisherman#335]
I would really appreciate an option to set the directory `fisherman` should store the plugins it downloads, using the `fish_function_path` to autoload the plugins.

That way we could keep `functions` for custom functions and maybe a `fisherman_functions` file dedicated for `fisherman` installed plugins.

**Comment by jbucaran** [comment]
@chamini2 

You can achieve this (or close enough) using the `fish_path` variable. 

See https://github.com/fisherman/fisherman#where-does-fisherman-put-stuff
>
> The configuration and cache are saved to ~/.config/fisherman and ~/.cache/fisherman respectively.
>
> The fishfile and plugins are saved to ~/.config/fish by default.
>
> To customize this location:
> ```fish
> set -U fish_path ~/my/path
> ```



You can customize the

**Comment by chamini2** [comment]
shouldn't it be `fisher_path`? `fish_path` seems it could mess with other `fish` stuff.

**Comment by nagromc** [comment]
@chamini2 Yes, it is quite confusing, but you have to understand `$fish_path` as seen by `fisherman`. The `fisher.fish` script uses `$fish_path` to target the default `fish` directory to make it work out-of-the-box. But as pointed out earlier, you can change `$fish_path` to another path to prevent `fisherman` from polluting your `fish` directory (`~/.config/fish` by default).

For instance, I set `$fish_path` to `~/.config/fish/fisherman` so that my `~/.config/fish/functions` remains clean when I run `fisher install <package>`, as my `~/.config/fish/functions` is under VCS control (dotfiles).

**Comment by jbucaran** [comment]
@chamini2 Sorry for the confusion, but given that it targets the fish directory and not the fisherman directory, that's the best name we came up with. Anyway, it won't mess with any other fish stuff.

I also have little to add to @nagromc's answer.

Cheers.
