### ISSUE TITLE
Custom functions and fisherman plugin functions are mixed 

### ISSUE THREAD

**Issue by jlesquembre** [fisherman/fisherman#340]
First of all, thanks for writing fisherman, it is great!

I have some custom files at `~/.config/fish/functions/`. When I install a fisherman plugin, fisherman pollutes this directory, making difficult to know which files are the custom ones and which ones belong to the plugins. I want to keep my custom files and the plugin files separately.
It looks like that I'm not the only one thinking that this is a problem, see [laughedelic fish dotfiles](https://github.com/laughedelic/fish)

As far as I know, fisherman creates symlinks for plugin files at `~/.config/fish/` under three directories, `completions.`, `conf.d/` and `functions/`. (Correct me if I'm wrong) 
To be able to keep plugin files and my custom files separate, I added these lines to my `config.fish` file:

```
set -U fish_path $HOME/dotfiles/fisherman

set fish_function_path $fish_path/functions $fish_function_path
set fish_complete_path $fish_path/completions $fish_complete_path
for file in $fish_path/conf.d/*.fish
    source $file
end
```

I think it makes sense if fisherman detects if the variable `fish_path` was set by the user, and in that case run an (improved version) of my script. It would be even better if by default no symlinks are created at `~/.config/fish` directory, but not sure if that is possible without breaking changes.

Thoughts?

**Comment by jbucaran** [comment]
@jlesquembre Hi there!

$fish_path was created for use cases like yours. Your script is good and is essentially what fish does too in ~/.config/fish at the start of the shell, great.

One of fisherman's features is that it does not rely on your fish configuration to be usable, it's just a function. This means fisherman is configuration agnostic, you don't even need a config.fish if that's your preference. Another thing is shell startup is not affected by fisherman, since there is no init code that needs to run for a default setup.

In your case, you wish to separate ~/.config/fish/{functions,conf.d,completions} from $fish_path/{functions,conf.d,completions} and I think that's a reasonable preference, but in my experience, using plugins and fisherman to handle them is better than managing functions, init scripts (conf.d) and completions oneself, hence the default behavior (which is harmless and does not affect any existing configuration).

If fisherman added a default configuration like what you are using, then it would potentially be less compatible with user's existing config if any.
