### ISSUE TITLE
How to contribute a new plugin?

### ISSUE THREAD

**Issue by orefalo** [fisherman/fisherman#353]
Send email, no answers so far... how does one contribute a new plugin?

**Comment by jbucaran** [comment]
@orefalo Hi there! I No one has been monitoring that email IIRC. Thanks for reminding me too.

If you'd like to publish the plugin, so that it is available to everyone when running `fisher ls-remote`, you are welcome to join the organization and create the repo/s.

You are also welcome to join <http://join.fisherman.sh>.

Cheers!
