### ISSUE TITLE
Error when running fisherman in termux

### ISSUE THREAD

**Issue by simonsmh** [fisherman/fisherman#375]
`An error occurred while redirecting file '/dev/stderr'
open: unknown error (errno was 13)`

**Comment by jbucaran** [comment]
@simonsmh Hi, I'm pretty sure this could be fixed if we replace `/dev/stderr` with `2>&1` or whatever was the right syntax, I can't always remember off the top of my head 😄.

PR much welcome! 👍

**Comment by christianrondeau** [comment]
I started looking at this, and in general using `>&2` works... But there's this one that is bugging me:

    set -g __fisher_stderr /dev/stderr

Since I'm using redirection rather than a "file", I would need to replace that everywhere, but why does this exists in the first place?

Otherwise, what *should* be there? I can't use `&2` here. 

An idea? Thanks!

**Comment by jbucaran** [comment]
@christianrondeau This exists because then it's very easy to assign /dev/null to `__fisher_stderr` to mute the channel for one or another reason.

I don't use termux, so I can't test this easily.

**Comment by christianrondeau** [comment]
Ok, I'll try to find a way to get the `/dev/stderr` real file descriptor, since there seems to be no redirection for this in termux (but `&2` does work). I'll fiddle around, but I'm afraid even though it's simple, it might be a pretty "big" change. I'll get back to you on that in a few weeks.

**Comment by jbucaran** [comment]
@christianrondeau I would not mind changing everything to use fish 1 and 2 descriptors at all and remove all the /dev/stderr, /dev/null, etc., as long as we don't break things! 😅

**Comment by christianrondeau** [comment]
Ok I made a proof of concept (there's a few todo in there), I'm going on vacation and I'm just trying out fish shell, so if someone wants to take over please do :) 

https://github.com/christianrondeau/fisherman/compare/master...christianrondeau:termux

Otherwise I'll try to finish this PR sometime in the future. If you have feedback on the direction I'm taking, let me know :)

**Comment by christianrondeau** [comment]
Hi! Quick update (yes, I'm coding on vacation, who would have thought? :P ) - I finished the branch and it's pretty much ready, but I don't have a Linux machine to test on, so even though it looks like it's working fine in Termux, there may be edge cases I have missed:

* I use $PREFIX to determine if termux is running. I'm sure there's a better way (like checking for /dev/stderr existence) but I'm not knowledgeable enough to make that call. Checking for termux would avoid false positives.
* The `__fisher_log` and `__fisher_get_key` functions were left untouched. I'm not sure how to make them work, and they were not used in the use cases I've checked

Here's the diff: https://github.com/christianrondeau/fisherman/compare/master...christianrondeau:termux

I won't be able to test on "real" Linux distributions this week. If you want, I can create a PR and let one of you guys check this out, or I can wait for next week. Any feedback in the meantime is welcome.

Thanks!

**Comment by jbucaran** [comment]
@christianrondeau Thanks! Next week is always good and yes, please, go ahead and create a PR when you can or better, when you get back! Enjoy your holidays. 👋

**Comment by christianrondeau** [comment]
A PR has been created: https://github.com/fisherman/fisherman/pull/383

**Comment by simonsmh** [comment]
Huge thanks!😋 Working now.
