### ISSUE TITLE
Loading abbreviations on plugin install

### ISSUE THREAD

**Issue by laughedelic** [fisherman/fisherman#394]
Hi. What is the usual way to persist the abbreviations list? I made a file with a list of `abbr` command calls, to be just sourced when I want to setup a new machine with my settings.

If there is no standard way of keeping abbreviations and other similar commands, it would be a nice feature to source some plugins files only once on installation (and update?).

**Comment by jbucaran** [comment]
@laughedelic I don't use abbreviations, but if I were you, I would create a "guarded" snippet that has all the `abbr` function calls and then sets a universal variable "on" so that the next time the snippet runs you skip running the `abbr` commands.

What do you think?

**Comment by laughedelic** [comment]
Hi! Sorry, I missed your comment.

This is, of course, a workaround. I was just thinking of some more convenient support from fisherman for this, like treating some conventionally named file in the plugin in a special way. 

Anyway, it's not a big deal, so if you're not interested in such feature and there's no much demand for it, you can close the issue, I'm going to use this workaround for myself.

**Comment by jbucaran** [comment]
I personally don't use `abbr` (avoid it rather), so it's not that important for me, but your idea could be completely implemented via a plugin and I am sure others would benefit from it, since `abbr` is a popular command.

**Comment by laughedelic** [comment]
> but your idea could be completely implemented via a plugin and I am sure others would benefit from it, since abbr is a popular command.

My point was a bit more general than just a special treatment of `abbr`. I mean more like a way for a plugin to "initialize" on install, which is a one time action not repeated on every fish load.

**Comment by jbucaran** [comment]
@laughedelic Yes, I see what you mean now. I am not against it, if someone wants to implement this and send a PR, I would be glad to help debug it or review it.

I'd **personally** prefer to keep what plugins can and can't do to a bare minimum, but that's just me. I want fisherman to evolve and adapt to whatever you and other users want, that's why I am still helping to maintain the project nowadays. 

Lately, I like fin more, but even fin had to make some compromises in the name of backward compatibility. Maybe when I get some free time I'll start something new with a different set of ideals.
