### ISSUE TITLE
Plugin not enabled after installation

### ISSUE THREAD

**Issue by DjebbZ** [fisherman/fisherman#395]
Hello,

I installed the following plugin https://github.com/jichu4n/fish-command-timer, installation went fine, plugin file is located at both places `~/.{cache,config}/fisherman/command-timer/fish_command_timer.fish` (looks normal to me), it's listed the fishfile (line `jichu4n/fish-command-timer` exists) but the plugin is not enabled. I have to manually call the `fish_command_timer` command in the shell or `source` the file in my fish config file.

Is it normal ? Looking briefly at the source code of fisherman, it seems that after installing a plugin it tries to enable it.

Env :

Arch Linux up-to-date
fish, version 2.6.0
fisherman version 2.13.0 ~/.config/fish/functions/fisher.fish
xfce4-terminal up-to-date (in case it's useful)

Thanks in advance.

**Comment by DjebbZ** [comment]
Note that the plugin says that it should be manually enabled like I said. My bad if I'm wrong when thinking that fisherman handled this automatically.

**Comment by jbucaran** [comment]
@DjebbZ Yep. The problem is, that this is not really a plugin, but a file with some code in it. Ideally, this software would be distributed as a fish ["configuration snippet"](https://fishshell.com/docs/current/index.html#initialization). 

From the fish docs:
> Configuration snippets in files ending in .fish, in the directories:
```
$XDG_CONFIG_HOME/fish/conf.d (by default, ~/.config/fish/conf.d/)
$__fish_sysconfdir/conf.d (by default, /etc/fish/conf.d)
/usr/share/fish/vendor_conf.d (set at compile time; by default, $__fish_datadir/conf.d)
```

Notice that snippets are a "fish-shell thing", not something made up in fishmerman.

If you must use this software, you have a few options:

1) Contact the author and try to convince him to rewrite that code as a legal fish snippet. Basically, put the code inside a conf.d directory and not ask users to `source` the file. 
2) Optionally fork that project and follow the steps above to fix it.

**Comment by jbucaran** [comment]
@DjebbZ Also check out [humanize_duration](https://github.com/fisherman/humanize_duration) and see if you can use it instead. 👋

**Comment by DjebbZ** [comment]
So fast !

I don't have the skills to develop it, I'd rather point the maintainer to this discussion. Thanks a lot !

**Comment by jbucaran** [comment]
@DjebbZ Cool. So, the "fishy" way would be to ask users to put that file inside ~/.config/conf.d instead of sourcing the file. This is still not enough for fisherman to pick it up, so if @jichu4n would be so kind to change their repo structure to this:

```
LICENSE
README.md	
conf.d/fish_command_timer.fish
```

then fisherman would be able to install that as plugin (snippet).

**Comment by DjebbZ** [comment]
I'm writing this exact Pull Request right now :smile: 

Your explanations are very precise, really appreciated.

**Comment by DjebbZ** [comment]
I'm almost there : I installed my fork locally, but had to open a new shell to see the results. I thought simply running `fisher .` in my fork would install *and* enable, seems it just installed it.

I'm asking so that I write proper instructions in the Pull Request. Thanks again !

**Comment by jbucaran** [comment]
@DjebbZ Just let me know what else you need from me. 👋

**Comment by DjebbZ** [comment]
here you go https://github.com/jichu4n/fish-command-timer/pull/15
