### ISSUE TITLE
What is the history of fisherman?

### ISSUE THREAD

**Issue by patrickf3139** [fisherman/fisherman#422]
Hi, I am still trying to decide between whether I want to use fisherman or OMF. I was leaning towards fisherman until I realized it seems the original author / biggest contributor to fisherman has deleted his account and support for fisherman has been scant. Can anyone shed some light on 

- the state of the fisherman community
- why they chose to use fisherman over OMF or vice-versa
- what happened to the biggest contributor who deleted his account

Thanks!

**Comment by gyakovlev** [comment]
@jorgebucaran , why did you delete your account? =)

**Comment by jorgebucaran** [comment]
@patrickf3139 

It's not too late for that, but at this point I'd rather start something new instead.

> the state of the fisherman community

There's a slack. I don't log in much these days, but surely it's still being used.

> why they chose to use fisherman over OMF or vice-versa

Some people use OMF, other people use fisherman, etc. Fisherman is stable.

> what happened to the biggest contributor who deleted his account

https://github.com/fisherman/fisherman/issues/307 didn't work out, so I lost interest in developing fisherman. In retrospect, I should've gone forward with my idea despite user feedback.

Maybe it's not too late, I don't know. If anyone wants to be in charge I'll gladly make you an admin in the org.

**Comment by patrickf3139** [comment]
Ah I see. Well thanks for your quick replies.

Ahh darn, I just read through the v3 proposal. I would've voted for it.

**Comment by gretel** [comment]
@jorgebucaran i am still using `fisherman` too and can't complain. i might still help out a bit in regards to 'something new'. regards

**Comment by dideler** [comment]
FWIW, here's the perspective of a fisherman user. Keep in mind it's all just opinions.

> the state of the fisherman community

Judging by my notifications from following OMF and fisherman, OMF is more active, if that's something that matters to you.

> why they chose to use fisherman over OMF or vice-versa

I chose fisherman because I liked the philosophy better. At the time it came across as a more minimalist and opinionated solution, whereas OMF came with all bells and whistles and tried to appeal to everyone which felt bloated to me. Not sure what the state is nowadays though, but I'm still a happy fisherman.

**Comment by patrickf3139** [comment]
Hi dideler, I just tried both of them and as far as I can tell, they are equally usable and have feature parity. Can you explain more about how fisherman is more minimalist and opinionated please? Thanks!

**Comment by jorgebucaran** [comment]
@patrickf3139 I think dideler meant more minimal and _less_ opinionated. But I could be wrong, as we all have different ways to evaluate software. See https://github.com/fisherman/fisherman/issues/69

**Comment by patrickf3139** [comment]
Hi again, I just want to say that after trying both, I've decided to go with fisherman. Thank you so much Jorge for developing this beautiful nifty tool and I hope you will continue maintaining it :)

**Comment by dideler** [comment]
Hey @patrickf3139, I liked that fisher had a philosophy and design guidelines similar to fish itself. To me, it felt like @jorgebucaran had a clear vision and would be more strict about what goes into it, rather than trying to please everyone in the community and the software potentially suffering from feature creep.

**Comment by jorgebucaran** [comment]
@patrickf3139 @dideler @gyakovlev @gretel  I just released [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉

**Comment by gretel** [comment]
> @patrickf3139 @dideler @gyakovlev @gretel I just released [fisher/releases/tag/3.0.0](https://github.com/jorgebucaran/fisher/releases/tag/3.0.0)~! 🎉

awesome! i was just recommending `fisher` to coworkers when i got this message 😄

**Comment by jorgebucaran** [comment]
Please be sure to see #450 if you are migrating from V2. 🙏

**Comment by jorgebucaran** [comment]
I will be adding more information to the README comparing fisher to other tools like fundle and Oh My Fish to help people choose in the future. 👋

**Comment by jorgebucaran** [comment]
Here is an up-to-date comparison between Fisher, Oh My Fish, and Fundle.

> :warning: **Disclaimer**: I'm the author of Fisher. I'm biased toward it. I'll try to make a fair comparison, but I'll probably fail. I may have missed something important. This information may be outdated by the time you read it. You should try them all and see which one works best for you.

## Summary

Fisher is a package manager. Like `npm`, `gem`, `brew`. Its function is to fetch fish scripts from an URL (with a bias toward GitHub) and put them in place so that your shell can find them. 

Fundle is also package manager. It can add, update and remove packages. Like Fisher it promotes a clean package structure. Its design is inspired by [Vundle.vim](https://github.com/VundleVim/Vundle.vim), but it has an interactive interface too. 

Oh My Fish is more than a package manager. It's a framework, package database, community-driven organization, and ecosystem. It started as an Oh My Zsh clone, making it appealing to fish-shell newcomers and shell neophytes alike. 

Oh My Fish and Fundle run code on startup to install (or enable) packages. This can potentially slow down your shell startup. YMMV. You may not care. Be your own judge. (See: https://github.com/danhper/fundle/issues/38)

My only criticism to Oh My Fish is their advocating of non-standard file and naming conventions: `*.load`, `init.fish`, `before.init.fish`, `key_bindings.fish` files, vendor-specific environment variables, hooks, and events which create framework lock-in/dependency.

## Technical Comparison

- **Fisher** is a package manager
  - Requires fish 2.0+
  - Optimizes download time if the package is hosted on GitHub, GitLab, and BitBucket
    - It does it by downloading tarballs instead of using git to clone
  - Supports self-hosted packages via ssh using a URL such as `owner@host.xz:path/to/repo`
  - Doesn't extend your configuration, modify your environment or run code on shell startup
  - Not a package registry
  - Includes no additional tools to help you scaffold or publish packages, core functions by default
  - Supports Oh My Fish packages, but 100% compatibility is not a goal
    - Packages using Oh My Fish non-standard extensions like `init.fish`, `uninstall.fish`, `key_bindings.fish` or recursive directories are supported (but strongly frowned upon as fish-shell has canonical alternatives and using Oh My Fish specific extensions create framework lock-in)
    - Packages using other Oh My Fish extensions such as `init_` events, Hooks, Oh My Fish core library functions, and Oh My Fish environment variables such as `$OMF_PATH`, `$package`, `$path` and `$dependencies` are not fully supported
  - Installs everything concurrently to maximize resource utilization
  - Caches everything—if you've installed a package before, you can install it again offline
  - Uses a lockfile (fishfile) to guarantee repeatable installations across systems
  - Resolves dependencies deterministically
    - It does it by diffing the fishfile to find out what needs to be added, updated, or removed
    - Package dependencies will be installed in the same way on any system, regardless of installation order
  - Uses the shell's canonical autorun mechanism (configuration snippets) to support packages with [key bindings out of the box](https://github.com/jorgebucaran/fisher/releases/tag/3.1.0#custom-key-bindings)
- **Oh My Fish** is a framework
  - Requires fish 2.2+
  - Consists of a package manager, startup configuration, core functions, a package scaffolding tool, a package registry, etc
  - Installs packages serially
  - Can install packages by name (if they exist in the package registry)
  - Modifies your fish function path on startup to force autoload of installed packages and add key bindings
    - More packages equals slower startup
  - Introduces non-standard file conventions such as `init.fish`, `uninstall.fish`, and `key_bindings.fish`
    - These conventions exist due to historical baggage and multiple clashing architecture redesigns
  - Supports packages with key binding through
- **Fundle** is a package manager
  - Requires fish 2.2+
  - Can add, update, and remove packages
    - Does not support package dependencies (fishfile)
    - Installs packages serially
    - Requires editing your fish configuration to manage packages
      - More packages equals slower startup

**Comment by jorgebucaran** [comment]
FYI https://github.com/jorgebucaran/fisher/issues/481
