### ISSUE TITLE
fisher command not found after immediately installing fisherman

### ISSUE THREAD

**Issue by patrickf3139** [fisherman/fisherman#439]
After installing fisherman through the recommended curl command, I tried to run the `fisher` command within the same shell and I got
```
fish: Unknown command 'fisher'
```
Not a huge deal. The solution is obviously to just open up a new fish shell or terminal tab and try again. But this does prevent me from automating the installation of fisherman completely in my dotfiles. And also it might confuse many new users. Any ideas what I can do to make `fisher` usable immediately after installing fisherman>

**Comment by Scrumplex** [comment]
Without any patches to fisherman itself you could just source the newly installed `.fish` file after installing.
```sh
source ~/.config/fish/functions/fisher.fish
```

**Comment by patrickf3139** [comment]
Thanks for the tip Sefa! I wonder if we can just patch fisherman to run that line at the end of the install command?

**Comment by Scrumplex** [comment]
The install command is no script. It is just curl saving a file to `.config/fish/functions/fisher.fish`

**Comment by patrickf3139** [comment]
Oh good point. I see that it'd be a much more complicated change.

**Comment by jorgebucaran** [comment]
@patrickf3139 I'm on macOS and I have been unable to reproduce this, fish picks it up immediately.

Here are a couple of ideas

- Source the fisher.fish file like @Scrumplex suggested
- Run the curl command inside a subshell 
- Use a `sleep 3` delay before you try to use `fisher` in your automation script


👋 Hope that works for you!

**Comment by patrickf3139** [comment]
@jorgebucaran So what you did to repro was
1. fisher self-destroy
2. open new tab/shell/whatever
3. re-create your fishfile in `~/.config/fish/fishfile`
4. execute 
```
curl -v -sLo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
fisher
```?

**Comment by patrickf3139** [comment]
Never mind I ran it manually outside of my script and it worked somehow. Ok must be a bug in my automation. Thanks Jorge.

**Comment by jorgebucaran** [comment]
@patrickf3139 As it turns out, fish [doesn't autoload functions immediately](https://github.com/fish-shell/fish-shell/blob/35c01bcba225a1341abf5a96b7fb9fa80715025c/src/autoload.cpp#L25) like I thought. 

It can take up to 15 seconds for fish to notice a new autoloaded function. That's the worst case so on average no more than 7.5 seconds.


Still, I am not able to reproduce this issue when installing using the `curl` command as described in the installation instructions.

Now, here is something that will definitely work if `fisher` is still not available after downloading it in your automation script:

```
exec fish
```

`exec` will replace the currently running shell with a new fish session. It will not result in a nested session, but a new one which will take over the old one (and that one will be destroyed). 

`fisher` should definitely be available in the new session. 💯

**Comment by patrickf3139** [comment]
Woohoo thank you @jorgebucaran !

**Comment by jorgebucaran** [comment]
@patrickf3139 FYI https://github.com/jorgebucaran/fisher/issues/477
