### ISSUE TITLE
Add plumbing function to update the index.

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#50]
This would be used instead of `fisher update --index` by those that need to cause the index to be updated for some reason. For example, _make_, during install, downloads the index for the first time. In this ocassion, using `fisher --update` will schedule the index update as a job in order to show a progress indicator which is not shown by make anyway and causes the install to fail in `< fish 2.2.0`.

Related: #48

**Comment by pawelmhm** [comment]
Just a small sidenote here. I also ran into some installation problems due to old fish version (in my case I had 2.0). Simple update to 2.2 helped and fixed my problem. Perhaps it would be easier for you to just warn people about updating their fish to most recent version? I think there may be lots of noise and pseudo-issues that will result from old fish versions.

**Comment by bucaran** [comment]
>  Perhaps it would be easier for you to just warn people about updating their fish to most recent version somewhere in docs

_Yes_. Will add a note in the Wiki too.

Thanks!

**Comment by bucaran** [comment]
bc2215b50ed7775f92048ff7f848142b9f23d786
