### ISSUE TITLE
Missing "what problem does this solve"

### ISSUE THREAD

**Issue by jwulf** [fisherman/fisherman#53]
Why do I want this thing - aside from the fact that it's shiny and new, and clearly it's useful enough for someone to take the time to build it....

I'm not sure why I'm installing this...

**Comment by jwulf** [comment]
Is it a replacement for omf?

**Comment by jwulf** [comment]
OK, I read the FAQ. Maybe a tagline like: 

Fisherman
Fish faster

A fast, modern plugin system for the fish shell.

**Comment by bucaran** [comment]
Totally. 

I just started working on the [Wiki](https://github.com/fisherman/fisherman/wiki).

First, I will add the Quickstart Guide. Then, fill in the Why Fisherman? and Fisherman Alternatives sections.

I like:

> A fast, modern plugin system for the fish shell.

What about:

> A fast, modern plugin system and CLI toolkit for the fish shell.

**Comment by bucaran** [comment]
For the record, and to answer your question now:


* Why do I want this thing?

If you are only using fish, you are missing out the ability to effectively share plugins, prompts, configs, missing completions, documentation for external utilities, plain old scripts or bundle of scripts.

If you are using Oh My Fish (OMF) / Wahoo or Tacklebox, you may be already doing some of the above, just very poorly.


***So***, I want to create shell scripts, snippets or let's call them utilities that follow the [UNIX guidelines](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) for option parsing, fish auto-completion out of the box, with bundled documentation using the traditional `man(1)` pages like a boss, and I want my scripts to come not only in the form of `.fish` files, but I want to ship them bundled with scripts in other languages too sometimes, maybe Awk or Perl, or if you are cool, Python. Then I want to commit that to a GitHub repository, or as a Gist, or to BitBucket, GitLabs or my own server if I want.

Fisherman makes this process very easy and it also gives me access to an external ["index"](https://github.com/fisherman/fisher-index) to where I can publish these utilities, let's better call them now **plugins** so that others can discover my stuff without having to know the URL in advance.

Fisherman is not like, say `brew` where you typically share one or more binaries, that's a true package manager indeed.

Fisherman, however, is about sharing snippets, prompts, configurations, initialization scripts, like I said above, that kind of stuff. In the Fisherman jargon, I am rolling all that into a bun and calling it "plugin". 

To Fisherman they are all the same, they **should** be, and if that's not the case your "framework", "manager", whatever, is not doing you any service.

There are several different setups that Fisherman understands and can process. Why? Because there are already existing snippets and plugins with their own idiosyncrasies. The same ones I mentioned above. Also people creating stuff in fish and releasing it without a particular "framework" in mind.

Fisherman recognizes packages from all of those dimensions and lets you install them and use them as you wish. Without strange restrictions that these other "frameworks" often pose on you, like strange name conventions or strict URL forms. It _will even__ try to guess the URL and correct your mistakes sometimes.

You can also "install" stuff locally and it will symlink a directory to Fisherman's configuration directory so that you can develop, test and iterate :repeat: fast and without having to do anything but `(1)` creating a directory and `(2)` typing `fisher install .` or `fisher install <my_path>`. You can commit your changes to a Git repo and that will not affect the process. It just works™.

But also you get a cache system to let you install stuff while offline (assuming you already downloaded the stuff first) and that segues into Fisherman's simplest, but best feature, the flat tree.
Here is the thing, Fisherman is as fast as no Fisherman. The initialization script basically declares a few variables and evaluates only those config files that you allow him to evaluate. On the other hand, OMF, Wahoo and Tacklebox mutate a variable to add/remove paths as you install/uninstall plugins. This is slower than loading all your functions into a single directory and telling fish to load only that. But wait, you say, a flat tree means every function will be public and there could be name collisions and what not. Unfortunately, there is not private function scope in fish. This is a "deficiency" (or feature) of the language and there is no way around this. You can add prefixes to your functions or use underscores at the beginning of the function name like everyone else does.
So, if fish has no private function scope, then it makes perfect sense to use a flat tree instead.
In the case of OMF and Wahoo things are even worse because these two systems use fish event handlers during the initialization process, and since fish does not automatically load files declaring events, they will source every single .fish file inside the plugin's directory and then call the emit EVENT_NAME builtin adding another step in the process.
And this is not even close to all, Fisherman has a lot of other cool things like the search command that parses the index file and lets you query plugins like you would expect from any modern tool. Each plugin gets a name, url, description, any number of tags and an author's name.
And if you install a plugin from an unknown URL, Fisherman will complete the information the best it can querying the Git repository and exhausting all the possibilities, so there's always data.
These "index", is just a plain text flat database written in a human readable format. This index is always kept up to date, there is no need to update the "framework" to see what new packages are available, you are always querying the latest index.
A few other features are strong ties to the UNIX way of thinking, everything is a stream and all commands can read the standard input to act as plumbing devices to let you do the lego work and build even more interesting stuff out of the few simple blocks Fisherman ships with. Another thing is Fishfiles (dependency manifest file) that allows plugins to declare dependencies to other plugins and keep track of what plugins you have installed or not in your system. Fisherman will recognize similar manifest files from other systems too.
Finally, the help is great. You are not alone. Everything is thoroughly documented in the form of UNIX man pages like it should be and the Wiki is also pretty nice.

**Comment by jwulf** [comment]
Don't lose your fish customisations when you migrate machines. 

Share them across machines easily.

**Comment by jwulf** [comment]
Write once, run anywhere!

;)

**Comment by pickfire** [comment]
Yeah, I think the prompt themes on `fish` is somewhat bloated, I hope that fisherman can work together with fish in that expect.

**Comment by bucaran** [comment]
Will leave this open to remind me to work on [Why Fisherman?](https://github.com/fisherman/fisherman/wiki/Why-Fisherman%3F).

**Comment by bucaran** [comment]
@jwulf I wrote a more thoughtful, still drafty, but with screencasts!, response [here](https://github.com/fisherman/fisherman/issues/69#issuecomment-179661994). Closing in favor of that.
