### ISSUE TITLE
Do you recommend installing Wahoo or Oh My Fish! themes/addons?

### ISSUE THREAD

**Issue by fishequality** [fisherman/fisherman#56]
Which ones should I use and why?

Here, they say that Wa packages are not compatible with OMF, is this true?

Related:
https://github.com/oh-my-fish/oh-my-fish/issues/212

**Comment by bucaran** [comment]
Fisherman is compatible with omf so I don't recommend against it. Specially themes, there are many good themes in the omf organization. Plugins are usually low quality, but there are some good ones.

Some omf themes like `bobthefish` and `agnoster` do work with Fisherman, but require you to reset the shell session. They work great with omf because **your session is reset after install with `exec fish`**. 

I tried fixing that, but as you can see in the following links:

+ https://github.com/oh-my-fish/theme-bobthefish/issues/18
+ https://github.com/oh-my-fish/theme-bobthefish/pull/19

They were not very cooperative. If you are looking for a powerline theme that's faster than bobthefish, I recommend [Shellder](https://github.com/simnalamburt/shellder) or use `bobthefish/agnoster` remembering you will have to reset the session only once after installing the first time.

**Comment by hauleth** [comment]
I am using Wahoo Agnoster theme (disclosure: I am author of that) with Fisherman and works pretty well:

![image](https://cloud.githubusercontent.com/assets/291639/12430286/28e83164-beef-11e5-82b6-c4e134062c5d.png)

There are 2 themes available:

- `agnoster default` (enabled by default)
- `agnoster powerline`

Just add one you like in your `config.fish` and enjoy.

**Comment by tobywf** [comment]
Ex-`omf` user here, used several themes with `fisherman` without much hassle;  including `bobthefish`. `bobthefish` is feature-rich, so I can see the appeal, especially if this is your first theme.

Because shell themes are a personal expression of your preferred workflow (and sometimes aesthetics), you might want to hack a theme to suit your needs. The restart issue @bucaran pointed out can become very annoying. I switched to `shellder` (and `fisherman`) for clean code and hackability. Hope that helps.

btw, @hauleth: great dotfiles!

**Comment by hauleth** [comment]
Thanks you very much. I am trying 😊

--
Łukasz Jan Niemier

Dnia 21 sty 2016 o godz. 00:46 Toby Fleming <notifications@github.com> napisał(a):

**Comment by bucaran** [comment]
Thanks everyon! Closing.
