### ISSUE TITLE
Why redirect install.fisherman.sh to a gist?

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman#57]
You could also use a git.io for url shortening.

**Comment by bucaran** [comment]
The reason is, a friend asked me so I implemented this feature as soon as I could.

In the future, instead of a Gist, I think this should redirect to either a file in this repo, or a new repo created for model installs. This way we could have opinionated installs outside the realm of this project, but still recognized under the organization.

**Comment by pickfire** [comment]
Oh, thanks a lot for the answer.

Good luck and have a nice day!

**Comment by bucaran** [comment]
Not a problem, keep them coming! :smile:

**Comment by pickfire** [comment]
@bucaran I had emailed you some problem too, should I open an issue for them?

**Comment by bucaran** [comment]
@pickfire Absolutely, feel free to open as many issues as you like! 

:anchor:
