### ISSUE TITLE
Maybe add a roadmap with a list of the features in the plans?

### ISSUE THREAD

**Issue by millaisnick** [fisherman/fisherman#62]
Something like:

* [ ] Add this nice feature
* [x] Improve this feature
* [ ] Etc

Just an idea.

**Comment by bucaran** [comment]
Maybe. Perhaps, after 0.5.0 or 0.6.0 once the feature set has stabilized. The new 0.5.0 has taken so long because I basically rewrote half of Fisherman and had to rewrite all tests too. This was good because I had a chance to simplify and refactor a lot of code too.

If we do add a roadmap where would you like to add it? README? Wiki?

**Comment by millaisnick** [comment]
Thanks. What about adding a new ROADMAP.md? Or just to the Readme, maybe.

**Comment by bucaran** [comment]
I'd rather add it to the README :smile:

**Comment by bucaran** [comment]
What are some features you would like to see / you need?

**Comment by bucaran** [comment]
This is the best I can do for you https://github.com/fisherman/fisherman/milestones

:smile: 

Feel free to leave open if you want to address this issue any further.

**Comment by bucaran** [comment]
@millaisnick Ping.

**Comment by millaisnick** [comment]
Thanks! Lgtm.
