### ISSUE TITLE
Fisher install doest not persist plugin

### ISSUE THREAD

**Issue by jonatas** [fisherman/fisherman#63]
When I install a new fisher plugin like:

```
fisher install https://github.com/jonatas/rd-fish
```

It works only in the same tab I am. If I open a new fish session. It does not load the plugin.

I missed something on my repo to load it in every fish session?

    $ fish -v # => fish, version 2.2.0
    $ fisher -v # => fisher version 0.4.0

**Comment by bucaran** [comment]
I looked at your plugin. You need to write a function per file and save it under `functions/`.

+ `rd-fish/functions/hrp.fish`

```fish
function hrp
  heroku run rails c --app rdstation-cedar
end
```

+ `rd-fish/functions/pglocks.fish`

```fish
function pglocks 
  heroku pg:locks --app rdstation-cedar2
end
```

+ `rd-fish/functions/hrs.fish` 

```fish
function hrs
  heroku run rails c --app rdstation-staging-cedar2
end
```

Also, it seems there is some code you always want to run during startup. You can do this in several ways, since Fisherman needs to support other framework styles. The way _I_ prefer is adding a file with the code you would like to source into a `conf.d` directory. But simply creating a `config.fish` at the root of your project works too.


+ `rd-fish/config.fish`
```
export RDMAIL=jonatas.paganini@resultadosdigitais.com.br

alias rd "cd ~/Code/rdstation; git status"
alias eu "echo 'eu = User.find_by(email: \'$RDMAIL\')' | pbcopy"

if status --is-interactive
    echo "Yay! rd-fish swimming!"
end
```

**Comment by jonatas** [comment]
Thank you @bucaran! Great explanation!

Is there any way to aggregate all my functions in the same file instead of put each one with correspondent file name under functions directory?


Like if I put on config.fish:

```
fish functions/all.fish
```

Will it expose my functions to fish shell?

**Comment by bucaran** [comment]
> Is there any way to aggregate all my functions in the same file instead of put each one with correspondent file name under functions directory?

Yes, you can do that too.

`rd-fish/config.fish`

```fish
function hrp
  heroku run rails c --app rdstation-cedar
end

function pglocks 
  heroku pg:locks --app rdstation-cedar2
end

function hrs
  heroku run rails c --app rdstation-staging-cedar2
end

export RDMAIL=jonatas.paganini@resultadosdigitais.com.br

alias rd "cd ~/Code/rdstation; git status"
alias eu "echo 'eu = User.find_by(email: \'$RDMAIL\')' | pbcopy"

if status --is-interactive
    echo "Yay! rd-fish swimming!"
end
```

**Comment by jonatas** [comment]
Thanks @bucaran !!! :cake:

**Comment by bucaran** [comment]
Thank you! :smile:
