### ISSUE TITLE
install omf/z does not work

### ISSUE THREAD

**Issue by fibo** [fisherman/fisherman#64]
Hi,

maybe I missed something, I tryed `fisher install omf/z` and I could not use z.
Also, I added a z.fish file in conf.d/ folder, see [my article](http://g14n.info/2016/01/welcome-to-fish-shell/) for complete working instructions. I did not found documentation about conf.d/, I just read the code. Is that ok?

**Comment by bucaran** [comment]
Good catch. There is little documentation for `conf.d` because this feature was added after I wrote and revised the documentation before 0.2.0 I think. The only thing I could find was:

```
fisher help install
```

```
...
In addition, any init.fish or *.config.fish files, are copied to $fisher_config/conf.d and evaluated during the start of the shell.
```

For OMF plugins you will often need the still-not-shipped :sweat_smile:  [omf plugin](https://gist.github.com/bucaran/7f12e6c6e0553b2666b2), but in the case of `z` things should be working alright because that plugin does not rely on events for anything special and it's just a function.

Can you show me the contents of your `$fisher_config/cache` and `$fisher_config/functions` directories?

**Comment by fibo** [comment]
Yes, I already have z, read [here how z plugin installation and setup](http://g14n.info/2016/01/welcome-to-fish-shell/#plugins) was completed successfully.

I tryed on another host, if I install fisherman, then `fisher install omf/z` I get a message

```
Installing >> z
Aye! 1 plugin/s installed in 2sm': /
```

Then even if I add z.fish into the conf.d/ folder, z does not work.

```
printf "%s\n" $fisher_config/{cache,functions}/*
No matches for wildcard '$fisher_config/{cache,functions}/*'.
fish: printf "%s\n" $fisher_config/{cache,functions}/*
```

While if I install it with `fisher install oh-my-fish/plugin-z` it works and in my cache I can see

```
printf "%s\n" $fisher_config/{cache,functions}/*
/home/io/.config/fisherman/cache/z
/home/io/.config/fisherman/functions/z.check.fish
/home/io/.config/fisherman/functions/z.fish
```

**Comment by fibo** [comment]
By the way, as you can see I stolen you animated gif :) How do create them?

**Comment by bucaran** [comment]
@fibo Mmm `fisher install` is working as it should as I can see both `z.fish` and `z.check.fish` inside the `functions/` directory in `$fisher_config`, so the problem is _not_ there. :white_check_mark: 

Now, 

> Then even if I add z.fish into the conf.d/ folder, z does not work.

There is a missunderstanding. You don't need to add anything to `conf.d`. The only thing that goes in there is code that should be evaluated at the start of the shell. In the case of `omf/z` there _is_ actually some code, but nothing other than checking whether you have `z` installed or not, so while you want that code eventually right now it's not telling us anything.

Can you confirm that `$fisher_config` is in `$fish_function_path`?

**Comment by bucaran** [comment]
@fibo One last thing:

```
git clone https://github.com/rupa/z
echo "set -g Z_SCRIPT_PATH ~/z/z.sh" >> ~/.config/fish/config.fish

**Comment by bucaran** [comment]
It seems to be working here.

![z](https://cloud.githubusercontent.com/assets/8317250/12655167/0b00ed50-c63b-11e5-9345-a0122f4cd31c.gif)

**Comment by fibo** [comment]
Thanks, I used `omf/plugin-z` instead of `omf/z` and now it works.

What I do not still understand is: does exists an `omf/z` plugin? If not, why `fisher` did not complain and said instead *installation complete*?

**Comment by bucaran** [comment]
@fibo Good point***!***

This is a problem with 0.4.0 and it is already fixed in 0.5.0, which will be shipping as soon as I am done with a few more tests.

**Comment by fibo** [comment]
Great, finally: is there a config I can set so I can get automatic updates or get notified, everytime I open fish shell or I use fisherman?
Something like bower message when it says "there is a new version available".

If not, can you put it on next release, so lazy People (like me :)) Will be Always up to date.

Btw I really like that fish has tests.

**Comment by bucaran** [comment]
@fibo _Yes!_ I like that. The issue is _when_ to check for updates. We don't want to block the session while Fisherman opens a network connection. 

For example, every time you install / search something, we could test the remote git status.

Can you create a separate issue for this? And close this one if you managed to get `z` working perfectly.

**Comment by fibo** [comment]
Sure: https://github.com/fisherman/fisherman/issues/65
