### ISSUE TITLE
Add awesome benchmark image in tag 0.5.0

### ISSUE THREAD

**Issue by pickfire** [fisherman/fisherman#67]
Hi, I hope that you could add the image to **top** of the wiki page https://github.com/fisherman/fisherman/wiki/Performance as I wasn't able to edit it.

![image](https://cloud.githubusercontent.com/assets/8317250/12727212/42790372-c95f-11e5-9f2d-7f78ff8303e9.png)

By the way, could you show some tips to create that nice image? What did you use?

**Comment by bucaran** [comment]
I updated the README with a more slim new graphic you can see below.

![bm](https://cloud.githubusercontent.com/assets/8317250/12776112/ac760080-ca96-11e5-8989-8aba002bdc2b.png)

As for the software, I used Pixelmator in this case.

I will add it to the Wiki too, thanks. :smile:

**Comment by pickfire** [comment]
Okay, thanks for sharing it to me.

**Comment by pickfire** [comment]
And I think that the `time -p fish -ic exit` is nice too, I hope that you don't delete it.

**Comment by bucaran** [comment]
I didn't, it's right there in the README. I took it from the graphic, but it's still written in the README.

**Comment by pickfire** [comment]
I think you should try the benchmark this way, the benchmark seems unreal.
```fish
fish --profile log.txt -c 'exit'
sort -k2 -n log.txt
```
I have heard it from @faho.

**Comment by bucaran** [comment]
I did, but that would only make everyone else look even worse. Fisherman footprint is in the order of microseconds. 

With a minimal user `config.fish`, these are my personal results:

<img width="1280" alt="screen shot 2016-02-12 at 6 03 34 pm" src="https://cloud.githubusercontent.com/assets/8317250/13027655/70fd124e-d29a-11e5-973c-9616d836db98.png">

**Comment by pickfire** [comment]
Oh, mine is 4 characters long:

![2016-02-13-204401_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/13027670/94f0646a-d292-11e5-99b9-265afcc40c99.png)

**Comment by bucaran** [comment]
IMO you can't make Fisherman run any _much_ faster, I will continue to add micro-optimizations here and there, whenever I can, but perhaps it's time to focus on improving performance of individual commands now. If you can find any bottlenecks or anything worth revisiting, let me know. We are approaching 1.0.

**Comment by faho** [comment]
@bucaran: You'll want to sort by the second field - i.e. `sort -k 2 --numeric-sort`.

What you showed in your image is how long the invidiual calls (which are the last things done by that fish instance) took - and `set -g` or `exit` are uninteresting because they are never bottlenecks. Though it looks like fisherman itself is faster than sourcing fish's __fish_datadir/config.fish - the slow part of which being the OSX-specific load_path_helper.

**Comment by pickfire** [comment]
@faho, thanks for coming here, I don't seem interested testing the abbr thing when I should add it to config.fish

@bucaran Give me some time to translate that page.

Sorry, I am a little busy now. Still moving forward.

**Comment by bucaran** [comment]
@faho If you look at Fisherman's [`config.fish`](https://github.com/fisherman/fisherman/blob/master/config.fish), you can guess, startup time still depends on what goes inside your `conf.d`, but other than that, it's obviously it loads as fast as fish itself because there is virtually nothing to run there.

Having almost no code of its own, saying Fisherman loads fast should be no surprise. If I sort the DAG results, I also get fish startup profile, which should be roughly the same for other users and has little to do with Fisherman.
