### ISSUE TITLE
`fisher (un)install` without arguments doesn't exit properly

### ISSUE THREAD

**Issue by kehugter** [fisherman/fisherman#70]
It keeps waiting for input. Should display usage, I guess.

fisher 0.5.0

**Comment by bucaran** [comment]
Uninstall, as well as Install, actually most Fisherman commands, read the standard input by default if no argumentts are given.

Sample output:
```
fisher uninstall
a
b
c
CTRL^D
Uninstalling (1 of 3) >> a
Uninstalling (2 of 3) >> b
Uninstalling (3 of 3) >> c
3 plugin/s uninstalled in 4s
```

**Comment by kehugter** [comment]
Wrongly guessed, then. Thanks for fisherman and your detailed answers, I've been reading the issue tracker for the last couple of hours.

**Comment by bucaran** [comment]
BTW I am not against changing the APIs before we ship 1.0.

Originally, that was `fisher update` behavior too, but a lot of people commented that `update`'s most normal behavior is to update Fisherman itself, so it became that way.

Update Fisherman

```
fisher update
```

Notice that the following works too.

```
fisher update me # or fisher update fisherman
```

Now, if you want to read from stdin with update, use a dash like good ol' UNIX fishermen.

```
fisher -l | fisher update -
```

Will update all the currently installed plugins. 

Now, the above will fail in 0.5.0 because we have a new feature that adds decoration to the listing. I am working on a patch for that right now that will remove both `*` and `>` from the input when they are the first character of a string.
