### ISSUE TITLE
I has installed omf/plugin-z , but it does't work

### ISSUE THREAD

**Issue by wensonsmith** [fisherman/fisherman#91]
i use this command 

```bash
fisher install omf/plugin-z
```

Install success!

![image](https://cloud.githubusercontent.com/assets/2544185/12949226/b4628268-d041-11e5-8e63-f50dc14156f2.png)

but i can't use it 

![image](https://cloud.githubusercontent.com/assets/2544185/12949256/d553e2dc-d041-11e5-8995-ee8cf2399c13.png)

**Comment by bucaran** [comment]
@wensonsmith Hi! Did you set `set -g Z_SCRIPT_PATH path/to/z`?

**Comment by bucaran** [comment]
@wensonsmith

**Comment by bucaran** [comment]
@wensonsmith

**Comment by wensonsmith** [comment]
Yes, i have installed the legacy 
![qq20160211-0 2x](https://cloud.githubusercontent.com/assets/2544185/12970090/0516f6c0-d0c5-11e5-9cf9-141f707d40ca.png)


But i don't know the path to z ,   so is this path right ?

![image](https://cloud.githubusercontent.com/assets/2544185/12970089/ffad8f5a-d0c4-11e5-87a4-17f5e2e3c3b1.png)

**Comment by wensonsmith** [comment]
I try to set like this 

![image](https://cloud.githubusercontent.com/assets/2544185/12970125/7bd9c3fa-d0c5-11e5-84ba-6ee4b2dc89ce.png)


but it still not work

![image](https://cloud.githubusercontent.com/assets/2544185/12970127/86dd2170-d0c5-11e5-852d-78ed5d9613b4.png)

Thank you very much!!

**Comment by bucaran** [comment]
Alright, first things first.

Do not mix your configuration code with Fisherman's configuration, that won't lead to any good! :pray: 

Next:

```
git clone https://github.com/rupa/z $HOME
```

That will download it to your home directory, so now you know `Z_SCRIPT_PATH` should be `$HOME/z`. Move `z` to your preferred directory, but make a note to remember where you put it.

Next, I assume your fish `config.fish` is in `~/.config`, so:

```
echo 'set -g Z_SCRIPT_PATH ~/z' >> ~/.config/fish/config.fish
```

Install `legacy` and `omf/plugin-z` and you are done.


<hr>

**Note**: I suspect the problem is you were confusing `rupa/z` with omf/plugin-z`. The first is the actual `Z` utility written in bash, the second is a plugin for fish that wraps `Z`'s into a function that does this:

```fish
cd (bash -c "source $Z_SCRIPT_PATH; _z $argv; echo \$PWD")
```


@wensonsmith

**Comment by wensonsmith** [comment]
Thanks !!  You are  AWESOME!!

I do as what you say, now it does't report error, but there is no effect .  I think there are some compatibility issues with the plugin-z.

![image](https://cloud.githubusercontent.com/assets/2544185/12971403/cb5683ea-d0d5-11e5-8f58-28b907510942.png)

Thank you for your patience！

**Comment by bucaran** [comment]
Can you try this?

```
type z
```

If the function definition is the same as this one [here](https://github.com/oh-my-fish/plugin-z/tree/master/functions), then maybe the problem is with the plugin itself.

Also try this:

```
cat $fisher_config/conf.d/z.init.fish 
```

**Comment by wensonsmith** [comment]
I uninstall all the plugins , and after reinstall , it works ..

thank you !

**Comment by bucaran** [comment]
@wensonsmith No problem, and don't hesitate to continue the discussion as I am here to help you troubleshoot the problem until you find a solution.

Cheers!
