### ISSUE TITLE
tmux-zen compatibility?

### ISSUE THREAD

**Issue by ewilliam** [fisherman/fisherman#93]
How do I get [tmux-zen](https://github.com/coderstephen/tmux-zen) to work with Fisherman? Install doesn't get it working...

**Comment by bucaran** [comment]
Can you describe the problem exactly?

I think the problem is that the plugin `tmux-zen` uses a `bundle` file declaring a dependency to another plugin, `config`, which **is not** in Fisherman's index. 

Looking at `config`'s source code, that plugin is very OMF-specific, as it uses `$OMF_` like variables which are unlikely to be supported in Fisherman.

So, effectively, the plugin `tmux-zen` is locked to OMF-only due to its coupled design. 

Fisherman already supports several of OMF unique quirks, but this one is going to be hard to patch.

I would never do this, as I hate duplicating code, but would you consider creating a new `tmux-zen` plugin which is not coupled to any framework?

I have created the [Fishery](https://github.com/fishery), especially with this purpose in mind. As it stands right now, not a lot of plugins are to be found, but it's growing every day. Your plugin would fit perfectly there, then we would add it to the index to allow for a simple `fisher install tmux-zen` install.

**Comment by bucaran** [comment]
@ewilliam I think there is not a lot I can do at this point, maybe someone will come up with a tmux-zen-like plugin for Fisherman.

**Comment by ewilliam** [comment]
understandable! i might consider doing `tmux-zen` myself someday. on a separate note, I just created my first fish/erman plugin, https://github.com/ewilliam/import-aliases

is this satisfactory? if so, how do i get this added to Fishery? let me know, thanks!

**Comment by bucaran** [comment]
@ewilliam Thanks! I left you some comments in your repo. If you want to add it to the registry, please add some basic documentation and maybe a couple of tests?

* https://github.com/fisherman/fisher-index

:+1:
