### ISSUE TITLE
Best practices for storing/initializing environment?

### ISSUE THREAD

**Issue by andrew-kennedy** [fisherman/fisherman#98]
So despite reading essentially all of the fisherman wiki, I'm still a bit confused as to where the best place to save my environment variables would be. Would it be in a custom plugin in the myplugin.config.fish file? Or somewhere else? I'm mostly concerned so I can then symlink these environment vars from my dotfiles to easily restore the state of fish/fisherman in the event of a machine reset/OS reinstall.

**Comment by bucaran** [comment]
@andrew-kennedy You can add your variables and other desired configuration to your `config.fish` and add any code **before** or **after** (after if you want to override any Fisherman defaults) Fisherman configuration that was added after the install.

**Comment by andrew-kennedy** [comment]
@bucaran 

> I suggest you simply put your configuration in your config.fish after Fisherman's own 3 line setup.

Will do, thanks!

**Comment by bucaran** [comment]
About adding functions, you can put them inside `~/.config/fish/functions` as you would expect :+1: 

One thing to be are of tis that `$fisher_home/functions` are always before your user functions in the `$fish_function_path`. This was an early design decision in order to prevent users from redefining core functions by mistake or by means **other than though plugins** (which is the recommended way to redefine Fisherman's core). 

In other words, you are free to create a plugin that modifies a Fisherman core function, but you can't redefine a Fisherman function privately by saving it to your `~/.config/fish/functions`. 

Here is the rationale, if you found a bug in a Fisherman function, instead of creating a private patch send it upstream!

If you created a function that overrides a Fisherman core feature, create a plugin. This way the community can benefit from your code whenever you are ready to publish it.

For an example of a plugin that takes advantage of this, see [`autoinit`](https://github.com/fishery/autoinit), which is how OhMyFish! and Wahoo `init_*` events are supported in Fisherman for those using legacy plugins.

**Comment by bucaran** [comment]
@andrew-kennedy Let me know if this makes sense and if you need help with anything else. Also whatever you end up doing too, please share it :smile:. This knowledge will be useful to future adopters.

Join the [Slack room](https://fisherman-wharf.herokuapp.com) too if you have a chance.

**Comment by bucaran** [comment]
@andrew-kennedy You may also be interested in checking out these casts I made in the other issue.

https://github.com/fisherman/fisherman/issues/97#issuecomment-183142068

**Comment by bucaran** [comment]
@andrew-kennedy Thank you for the questions. Feel free to reopen or create a new issue if you have more questions. I am closing this for now. :+1:
