### ISSUE TITLE
Improve the update mechanism, it kinda sucks :)

### ISSUE THREAD

**Issue by bucaran** [fisherman/fisherman#99]
Some users keep having problems updating Fisherman, some people have even removed Fisherman and installed it again from scratch to get to the latest version. I don't have a lot of evidence, but I have heard accounts from several people. 

```
fisher update
```

Should sync `$fisher_home` to Fisherman's latest version, period. If `git pull --rebase origin master` fails for some reason, we should try something more aggressive like a hard reset or in the case of total disaster, wipe out `$fisher_home` and `git clone --depth 1 https://github.com/fisherman/fisherman $fisher_home`.

**Comment by daenney** [comment]
I'd be careful about doing total wipe-outs. People might have made local modifications so prompting them about it first is probably a safe way to go about this.

**Comment by bucaran** [comment]
What about checking the current branch? If you are on a branch that is not master, then we either abort the update or checkout master update and checkout your branch again.

One more thing, if we were on master and there were changes, we could stash them, but why would anyone be modifying Fisherman directly if they want to update?

Another approach is to remove the ability to update and distribute Fisherman with a package manager like brew or npm.

**Comment by daenney** [comment]
Well. I ran into this issue because of the bug in `0.5.0` with `find` on an empty directory so I lifted your patch into my `0.5.0` checkout to get rid of that bug until `0.6.0` came out.

**Comment by pickfire** [comment]
I have some trouble uninstalling before, I updated it from `0.4` to `0.5`, it's a bit problematic, I need to wipe `$fisher_home` and manually run the `curl | fish` command again.

@daenney, for that issue, I suggest checking for `git status` and `git log` *automatically* for **any local changes or patches**, if there's one, **prompt to ask them if they want a hard reset**.

This should be a better method, because during `0.5`, the update has create a duplicated clone and thus broke fisherman, so when there are changes to `$fisher_home` in the future, the upgrade can be safer.

**Comment by bucaran** [comment]
Closing in favor of #107.
